/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.2 ./maps/chunk75--100-lvl-1.glb --transform --resolution --shadows -o ./maps/chunk75--100-lvl-1-transformed.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/chunk75--100-lvl-1-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Stone.geometry} material={materials.stone} />
      <mesh castShadow receiveShadow geometry={nodes.Grass_Block.geometry} material={materials.grass_block_top} />
      <mesh castShadow receiveShadow geometry={nodes.Dirt.geometry} material={materials.dirt} />
      <mesh castShadow receiveShadow geometry={nodes.Spruce_Wood_Planks.geometry} material={materials.spruce_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Bedrock.geometry} material={materials.bedrock} />
      <mesh castShadow receiveShadow geometry={nodes.Stationary_Water.geometry} material={materials.water_still} />
      <mesh castShadow receiveShadow geometry={nodes.Sand.geometry} material={materials.sand} />
      <mesh castShadow receiveShadow geometry={nodes.Jungle_Wood.geometry} material={materials.jungle_log} />
      <mesh castShadow receiveShadow geometry={nodes.Oak_Leaves.geometry} material={materials.oak_leaves} />
      <mesh castShadow receiveShadow geometry={nodes.Spruce_Leaves.geometry} material={materials.spruce_leaves} />
      <mesh castShadow receiveShadow geometry={nodes.Birch_Leaves.geometry} material={materials.birch_leaves} />
      <mesh castShadow receiveShadow geometry={nodes.Jungle_Leaves.geometry} material={materials.jungle_leaves} />
      <mesh castShadow receiveShadow geometry={nodes.Grass.geometry} material={materials.grass} />
      <mesh castShadow receiveShadow geometry={nodes.Brown_Wool.geometry} material={materials.brown_wool} />
      <mesh castShadow receiveShadow geometry={nodes.Allium.geometry} material={materials.allium} />
      <mesh castShadow receiveShadow geometry={nodes.Mossy_Cobblestone.geometry} material={materials.mossy_cobblestone} />
      <mesh castShadow receiveShadow geometry={nodes.Mossy_Stone_Bricks.geometry} material={materials.mossy_stone_bricks} />
      <mesh castShadow receiveShadow geometry={nodes.Spruce_Slab.geometry} material={materials.spruce_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Emerald_Ore.geometry} material={materials.emerald_ore} />
      <mesh castShadow receiveShadow geometry={nodes.Spruce_Stairs.geometry} material={materials.spruce_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Mossy_Stone_Brick_Wall.geometry} material={materials.mossy_stone_bricks} />
      <mesh castShadow receiveShadow geometry={nodes.Potato.geometry} material={materials.potatoes_stage3} />
      <mesh castShadow receiveShadow geometry={nodes.Spruce_Fence.geometry} material={materials.spruce_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Mossy_Cobblestone_Slab.geometry} material={materials.mossy_cobblestone} />
      <mesh castShadow receiveShadow geometry={nodes.Spruce_Trapdoor.geometry} material={materials.spruce_trapdoor} />
      <mesh castShadow receiveShadow geometry={nodes.Seagrass.geometry} material={materials.tall_seagrass_top} />
      <mesh castShadow receiveShadow geometry={nodes.Lantern.geometry} material={materials.lantern} />
      <mesh castShadow receiveShadow geometry={nodes.Campfire.geometry} material={materials.campfire_log} />
      <mesh castShadow receiveShadow geometry={nodes.Moss_Block.geometry} material={materials.moss_block} />
      <mesh castShadow receiveShadow geometry={nodes.Mangrove_Leaves.geometry} material={materials.mangrove_leaves} />
      <mesh castShadow receiveShadow geometry={nodes.Bookshelf_1.geometry} material={materials.oak_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Bookshelf_2.geometry} material={materials.bookshelf} />
      <mesh castShadow receiveShadow geometry={nodes.Sunflower_1.geometry} material={materials.sunflower_back} />
      <mesh castShadow receiveShadow geometry={nodes.Sunflower_2.geometry} material={materials.sunflower_front} />
      <mesh castShadow receiveShadow geometry={nodes.Sunflower_3.geometry} material={materials.sunflower_bottom} />
      <mesh castShadow receiveShadow geometry={nodes.Sunflower_4.geometry} material={materials.sunflower_top} />
      <mesh castShadow receiveShadow geometry={nodes.Large_Fern_1.geometry} material={materials.large_fern_bottom} />
      <mesh castShadow receiveShadow geometry={nodes.Large_Fern_2.geometry} material={materials.large_fern_top} />
      <mesh castShadow receiveShadow geometry={nodes.Tall_Seagrass_1.geometry} material={materials.tall_seagrass_bottom} />
      <mesh castShadow receiveShadow geometry={nodes.Tall_Seagrass_2.geometry} material={materials.tall_seagrass_top} />
      <mesh castShadow receiveShadow geometry={nodes.Grindstone_1.geometry} material={materials.dark_oak_log} />
      <mesh castShadow receiveShadow geometry={nodes.Grindstone_2.geometry} material={materials.grindstone_side} />
      <mesh castShadow receiveShadow geometry={nodes.Grindstone_3.geometry} material={materials.grindstone_pivot} />
      <mesh castShadow receiveShadow geometry={nodes.Grindstone_4.geometry} material={materials.grindstone_round} />
    </group>
  )
}

useGLTF.preload('/chunk75--100-lvl-1-transformed.glb')
