/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.2 ./maps/chunk-75--325-lvl-1.glb --transform --resolution --shadows -o ./maps/chunk-75--325-lvl-1-transformed.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/chunk-75--325-lvl-1-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Polished_Andesite.geometry} material={materials.polished_andesite} />
      <mesh castShadow receiveShadow geometry={nodes.Spruce_Wood_Planks.geometry} material={materials.spruce_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Dark_Oak_Wood_Planks.geometry} material={materials.dark_oak_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Bedrock.geometry} material={materials.bedrock} />
      <mesh castShadow receiveShadow geometry={nodes.Spruce_Wood.geometry} material={materials.spruce_log} />
      <mesh castShadow receiveShadow geometry={nodes.Jungle_Wood.geometry} material={materials.jungle_log} />
      <mesh castShadow receiveShadow geometry={nodes.Oak_Leaves.geometry} material={materials.oak_leaves} />
      <mesh castShadow receiveShadow geometry={nodes.Birch_Leaves.geometry} material={materials.birch_leaves} />
      <mesh castShadow receiveShadow geometry={nodes.Jungle_Leaves.geometry} material={materials.jungle_leaves} />
      <mesh castShadow receiveShadow geometry={nodes.Grass.geometry} material={materials.grass} />
      <mesh castShadow receiveShadow geometry={nodes.Allium.geometry} material={materials.allium} />
      <mesh castShadow receiveShadow geometry={nodes.Azure_Bluet.geometry} material={materials.azure_bluet} />
      <mesh castShadow receiveShadow geometry={nodes.Stone_Brick_Slab.geometry} material={materials.stone_bricks} />
      <mesh castShadow receiveShadow geometry={nodes.Mossy_Cobblestone.geometry} material={materials.mossy_cobblestone} />
      <mesh castShadow receiveShadow geometry={nodes.Clay.geometry} material={materials.clay} />
      <mesh castShadow receiveShadow geometry={nodes.Green_Stained_Glass.geometry} material={materials.green_stained_glass} />
      <mesh castShadow receiveShadow geometry={nodes.Mossy_Stone_Bricks.geometry} material={materials.mossy_stone_bricks} />
      <mesh castShadow receiveShadow geometry={nodes.Stone_Brick_Stairs.geometry} material={materials.stone_bricks} />
      <mesh castShadow receiveShadow geometry={nodes.Andesite_Wall.geometry} material={materials.andesite} />
      <mesh castShadow receiveShadow geometry={nodes.Mossy_Stone_Brick_Wall.geometry} material={materials.mossy_stone_bricks} />
      <mesh castShadow receiveShadow geometry={nodes.Cyan_Terracotta.geometry} material={materials.cyan_terracotta} />
      <mesh castShadow receiveShadow geometry={nodes.Dark_Oak_Wood.geometry} material={materials.dark_oak_log} />
      <mesh castShadow receiveShadow geometry={nodes.Prismarine_Bricks.geometry} material={materials.prismarine_bricks} />
      <mesh castShadow receiveShadow geometry={nodes.Spruce_Fence.geometry} material={materials.spruce_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Prismarine_Brick_Slab.geometry} material={materials.prismarine_bricks} />
      <mesh castShadow receiveShadow geometry={nodes.Mossy_Cobblestone_Slab.geometry} material={materials.mossy_cobblestone} />
      <mesh castShadow receiveShadow geometry={nodes.Prismarine_Brick_Stairs.geometry} material={materials.prismarine_bricks} />
      <mesh castShadow receiveShadow geometry={nodes.Smooth_Stone.geometry} material={materials.smooth_stone} />
      <mesh castShadow receiveShadow geometry={nodes.Double_Polished_Andesite_Slab.geometry} material={materials.polished_andesite} />
      <mesh castShadow receiveShadow geometry={nodes.Polished_Andesite_Slab.geometry} material={materials.polished_andesite} />
      <mesh castShadow receiveShadow geometry={nodes.Polished_Diorite_Slab.geometry} material={materials.polished_diorite} />
      <mesh castShadow receiveShadow geometry={nodes.Polished_Diorite_Stairs.geometry} material={materials.polished_diorite} />
      <mesh castShadow receiveShadow geometry={nodes.Polished_Andesite_Stairs.geometry} material={materials.polished_andesite} />
      <mesh castShadow receiveShadow geometry={nodes.Mossy_Cobblestone_Stairs.geometry} material={materials.mossy_cobblestone} />
      <mesh castShadow receiveShadow geometry={nodes.Tuff.geometry} material={materials.tuff} />
      <mesh castShadow receiveShadow geometry={nodes.Moss_Block.geometry} material={materials.moss_block} />
      <mesh castShadow receiveShadow geometry={nodes.Lilac_1.geometry} material={materials.lilac_bottom} />
      <mesh castShadow receiveShadow geometry={nodes.Lilac_2.geometry} material={materials.lilac_top} />
      <mesh castShadow receiveShadow geometry={nodes.Large_Fern_1.geometry} material={materials.large_fern_bottom} />
      <mesh castShadow receiveShadow geometry={nodes.Large_Fern_2.geometry} material={materials.large_fern_top} />
      <mesh castShadow receiveShadow geometry={nodes.Bamboo_1.geometry} material={materials.bamboo_large_leaves} />
      <mesh castShadow receiveShadow geometry={nodes.Bamboo_2.geometry} material={materials.bamboo_small_leaves} />
      <mesh castShadow receiveShadow geometry={nodes.Bamboo_3.geometry} material={materials.bamboo_stalk} />
    </group>
  )
}

useGLTF.preload('/chunk-75--325-lvl-1-transformed.glb')
