/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.2 ./maps/chunk100--375-lvl-1.glb --transform --resolution --shadows -o ./maps/chunk100--375-lvl-1-transformed.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/chunk100--375-lvl-1-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Dark_Oak_Wood_Planks.geometry} material={materials.dark_oak_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Bedrock.geometry} material={materials.bedrock} />
      <mesh castShadow receiveShadow geometry={nodes.Spruce_Wood.geometry} material={materials.spruce_log} />
      <mesh castShadow receiveShadow geometry={nodes.Jungle_Wood.geometry} material={materials.jungle_log} />
      <mesh castShadow receiveShadow geometry={nodes.Oak_Leaves.geometry} material={materials.oak_leaves} />
      <mesh castShadow receiveShadow geometry={nodes.Birch_Leaves.geometry} material={materials.birch_leaves} />
      <mesh castShadow receiveShadow geometry={nodes.Jungle_Leaves.geometry} material={materials.jungle_leaves} />
      <mesh castShadow receiveShadow geometry={nodes.Grass.geometry} material={materials.grass} />
      <mesh castShadow receiveShadow geometry={nodes.Allium.geometry} material={materials.allium} />
      <mesh castShadow receiveShadow geometry={nodes.Azure_Bluet.geometry} material={materials.azure_bluet} />
      <mesh castShadow receiveShadow geometry={nodes.Nether_Brick.geometry} material={materials.nether_bricks} />
      <mesh castShadow receiveShadow geometry={nodes.Potato.geometry} material={materials.potatoes_stage3} />
      <mesh castShadow receiveShadow geometry={nodes.Cyan_Terracotta.geometry} material={materials.cyan_terracotta} />
      <mesh castShadow receiveShadow geometry={nodes.Dark_Oak_Wood.geometry} material={materials.dark_oak_log} />
      <mesh castShadow receiveShadow geometry={nodes.Spruce_Fence.geometry} material={materials.spruce_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Tuff.geometry} material={materials.tuff} />
      <mesh castShadow receiveShadow geometry={nodes.Moss_Block.geometry} material={materials.moss_block} />
      <mesh castShadow receiveShadow geometry={nodes.Green_Stained_Glass_Pane_1.geometry} material={materials.green_stained_glass} />
      <mesh castShadow receiveShadow geometry={nodes.Green_Stained_Glass_Pane_2.geometry} material={materials.green_stained_glass_pane_top} />
      <mesh castShadow receiveShadow geometry={nodes.Lilac_1.geometry} material={materials.lilac_bottom} />
      <mesh castShadow receiveShadow geometry={nodes.Lilac_2.geometry} material={materials.lilac_top} />
      <mesh castShadow receiveShadow geometry={nodes.Large_Fern_1.geometry} material={materials.large_fern_bottom} />
      <mesh castShadow receiveShadow geometry={nodes.Large_Fern_2.geometry} material={materials.large_fern_top} />
      <mesh castShadow receiveShadow geometry={nodes.Bamboo_1.geometry} material={materials.bamboo_large_leaves} />
      <mesh castShadow receiveShadow geometry={nodes.Bamboo_2.geometry} material={materials.bamboo_small_leaves} />
      <mesh castShadow receiveShadow geometry={nodes.Bamboo_3.geometry} material={materials.bamboo_stalk} />
    </group>
  )
}

useGLTF.preload('/chunk100--375-lvl-1-transformed.glb')
