/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.2 ./maps/chunk0--375-lvl-1.glb --transform --resolution --shadows -o ./maps/chunk0--375-lvl-1-transformed.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/chunk0--375-lvl-1-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Stone.geometry} material={materials.stone} />
      <mesh castShadow receiveShadow geometry={nodes.Polished_Diorite.geometry} material={materials.polished_diorite} />
      <mesh castShadow receiveShadow geometry={nodes.Andesite.geometry} material={materials.andesite} />
      <mesh castShadow receiveShadow geometry={nodes.Polished_Andesite.geometry} material={materials.polished_andesite} />
      <mesh castShadow receiveShadow geometry={nodes.Bedrock.geometry} material={materials.bedrock} />
      <mesh castShadow receiveShadow geometry={nodes.Oak_Leaves.geometry} material={materials.oak_leaves} />
      <mesh castShadow receiveShadow geometry={nodes.Jungle_Leaves.geometry} material={materials.jungle_leaves} />
      <mesh castShadow receiveShadow geometry={nodes.Sandstone.geometry} material={materials.sandstone} />
      <mesh castShadow receiveShadow geometry={nodes.Grass.geometry} material={materials.grass} />
      <mesh castShadow receiveShadow geometry={nodes.Allium.geometry} material={materials.allium} />
      <mesh castShadow receiveShadow geometry={nodes.Mossy_Cobblestone.geometry} material={materials.mossy_cobblestone} />
      <mesh castShadow receiveShadow geometry={nodes.Clay.geometry} material={materials.clay} />
      <mesh castShadow receiveShadow geometry={nodes.Mossy_Stone_Bricks.geometry} material={materials.mossy_stone_bricks} />
      <mesh castShadow receiveShadow geometry={nodes.Stone_Brick_Stairs.geometry} material={materials.stone_bricks} />
      <mesh castShadow receiveShadow geometry={nodes.Dark_Oak_Slab.geometry} material={materials.dark_oak_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Andesite_Wall.geometry} material={materials.andesite} />
      <mesh castShadow receiveShadow geometry={nodes.Mossy_Stone_Brick_Wall.geometry} material={materials.mossy_stone_bricks} />
      <mesh castShadow receiveShadow geometry={nodes.Potato.geometry} material={materials.potatoes_stage3} />
      <mesh castShadow receiveShadow geometry={nodes.Dark_Oak_Stairs.geometry} material={materials.dark_oak_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Prismarine_Bricks.geometry} material={materials.prismarine_bricks} />
      <mesh castShadow receiveShadow geometry={nodes.Dark_Oak_Fence.geometry} material={materials.dark_oak_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Prismarine_Brick_Slab.geometry} material={materials.prismarine_bricks} />
      <mesh castShadow receiveShadow geometry={nodes.Mossy_Stone_Brick_Slab.geometry} material={materials.mossy_stone_bricks} />
      <mesh castShadow receiveShadow geometry={nodes.Prismarine_Brick_Slab_1.geometry} material={materials.prismarine_bricks} />
      <mesh castShadow receiveShadow geometry={nodes.Mossy_Stone_Brick_Slab_1.geometry} material={materials.mossy_stone_bricks} />
      <mesh castShadow receiveShadow geometry={nodes.Mossy_Cobblestone_Slab.geometry} material={materials.mossy_cobblestone} />
      <mesh castShadow receiveShadow geometry={nodes.Prismarine_Brick_Stairs.geometry} material={materials.prismarine_bricks} />
      <mesh castShadow receiveShadow geometry={nodes.Smooth_Stone.geometry} material={materials.smooth_stone} />
      <mesh castShadow receiveShadow geometry={nodes.Bamboo.geometry} material={materials.bamboo_stalk} />
      <mesh castShadow receiveShadow geometry={nodes.Double_Polished_Andesite_Slab.geometry} material={materials.polished_andesite} />
      <mesh castShadow receiveShadow geometry={nodes.Polished_Andesite_Slab.geometry} material={materials.polished_andesite} />
      <mesh castShadow receiveShadow geometry={nodes.Polished_Diorite_Slab.geometry} material={materials.polished_diorite} />
      <mesh castShadow receiveShadow geometry={nodes.Polished_Diorite_Stairs.geometry} material={materials.polished_diorite} />
      <mesh castShadow receiveShadow geometry={nodes.Polished_Andesite_Stairs.geometry} material={materials.polished_andesite} />
      <mesh castShadow receiveShadow geometry={nodes.Mossy_Stone_Brick_Stairs.geometry} material={materials.mossy_stone_bricks} />
      <mesh castShadow receiveShadow geometry={nodes.Mossy_Cobblestone_Stairs.geometry} material={materials.mossy_cobblestone} />
      <mesh castShadow receiveShadow geometry={nodes.Tuff.geometry} material={materials.tuff} />
      <mesh castShadow receiveShadow geometry={nodes.Oxidized_Copper.geometry} material={materials.oxidized_copper} />
      <mesh castShadow receiveShadow geometry={nodes.Moss_Block.geometry} material={materials.moss_block} />
      <mesh castShadow receiveShadow geometry={nodes.Stationary_Water_1.geometry} material={materials.water_still} />
      <mesh castShadow receiveShadow geometry={nodes.Stationary_Water_2.geometry} material={materials.water_flow} />
      <mesh castShadow receiveShadow geometry={nodes.Lilac_1.geometry} material={materials.lilac_bottom} />
      <mesh castShadow receiveShadow geometry={nodes.Lilac_2.geometry} material={materials.lilac_top} />
      <mesh castShadow receiveShadow geometry={nodes.Large_Fern_1.geometry} material={materials.large_fern_bottom} />
      <mesh castShadow receiveShadow geometry={nodes.Large_Fern_2.geometry} material={materials.large_fern_top} />
    </group>
  )
}

useGLTF.preload('/chunk0--375-lvl-1-transformed.glb')
