/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.2 ./maps/chunk100--200-lvl-1.glb --transform --resolution --shadows -o ./maps/chunk100--200-lvl-1-transformed.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/chunk100--200-lvl-1-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Stone.geometry} material={materials.stone} />
      <mesh castShadow receiveShadow geometry={nodes.Granite.geometry} material={materials.granite} />
      <mesh castShadow receiveShadow geometry={nodes.Andesite.geometry} material={materials.andesite} />
      <mesh castShadow receiveShadow geometry={nodes.Polished_Andesite.geometry} material={materials.polished_andesite} />
      <mesh castShadow receiveShadow geometry={nodes.Grass_Block.geometry} material={materials.grass_block_top} />
      <mesh castShadow receiveShadow geometry={nodes.Dirt.geometry} material={materials.dirt} />
      <mesh castShadow receiveShadow geometry={nodes.Jungle_Wood_Planks.geometry} material={materials.jungle_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Bedrock.geometry} material={materials.bedrock} />
      <mesh castShadow receiveShadow geometry={nodes.Stationary_Water.geometry} material={materials.water_still} />
      <mesh castShadow receiveShadow geometry={nodes.Iron_Ore.geometry} material={materials.iron_ore} />
      <mesh castShadow receiveShadow geometry={nodes.Grass.geometry} material={materials.grass} />
      <mesh castShadow receiveShadow geometry={nodes.Brown_Wool.geometry} material={materials.brown_wool} />
      <mesh castShadow receiveShadow geometry={nodes.Stone_Brick_Slab.geometry} material={materials.stone_bricks} />
      <mesh castShadow receiveShadow geometry={nodes.Mossy_Cobblestone.geometry} material={materials.mossy_cobblestone} />
      <mesh castShadow receiveShadow geometry={nodes.Mossy_Stone_Bricks.geometry} material={materials.mossy_stone_bricks} />
      <mesh castShadow receiveShadow geometry={nodes.Stone_Brick_Stairs.geometry} material={materials.stone_bricks} />
      <mesh castShadow receiveShadow geometry={nodes.Double_Spruce_Slab.geometry} material={materials.spruce_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Spruce_Slab.geometry} material={materials.spruce_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Jungle_Slab.geometry} material={materials.jungle_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Jungle_Stairs.geometry} material={materials.jungle_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Light_Carpet.geometry} material={materials.light_gray_wool} />
      <mesh castShadow receiveShadow geometry={nodes.Moss_Carpet.geometry} material={materials.moss_block} />
      <mesh castShadow receiveShadow geometry={nodes.Jungle_Fence_Gate.geometry} material={materials.jungle_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Spruce_Fence.geometry} material={materials.spruce_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Brown_Concrete.geometry} material={materials.brown_concrete} />
      <mesh castShadow receiveShadow geometry={nodes.Stripped_Spruce_Wood.geometry} material={materials.stripped_spruce_log} />
      <mesh castShadow receiveShadow geometry={nodes.Stripped_Jungle_Wood.geometry} material={materials.stripped_jungle_log} />
      <mesh castShadow receiveShadow geometry={nodes.Lantern.geometry} material={materials.lantern} />
      <mesh castShadow receiveShadow geometry={nodes.Chain.geometry} material={materials.chain} />
      <mesh castShadow receiveShadow geometry={nodes.Stone_Stairs.geometry} material={materials.stone} />
      <mesh castShadow receiveShadow geometry={nodes.Polished_Andesite_Stairs.geometry} material={materials.polished_andesite} />
      <mesh castShadow receiveShadow geometry={nodes.Block_of_Amethyst.geometry} material={materials.amethyst_block} />
      <mesh castShadow receiveShadow geometry={nodes.Waxed_Oxidized_Cut_Copper.geometry} material={materials.oxidized_cut_copper} />
      <mesh castShadow receiveShadow geometry={nodes.Moss_Block.geometry} material={materials.moss_block} />
      <mesh castShadow receiveShadow geometry={nodes.Waxed_Oxidized_Cut_Copper_Slab.geometry} material={materials.oxidized_cut_copper} />
      <mesh castShadow receiveShadow geometry={nodes.Crafting_Table_1.geometry} material={materials.oak_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Crafting_Table_2.geometry} material={materials.crafting_table_top} />
      <mesh castShadow receiveShadow geometry={nodes.Crafting_Table_3.geometry} material={materials.crafting_table_side} />
      <mesh castShadow receiveShadow geometry={nodes.Crafting_Table_4.geometry} material={materials.crafting_table_front} />
      <mesh castShadow receiveShadow geometry={nodes.Barrel_1.geometry} material={materials.barrel_top} />
      <mesh castShadow receiveShadow geometry={nodes.Barrel_2.geometry} material={materials.barrel_side} />
      <mesh castShadow receiveShadow geometry={nodes.Barrel_3.geometry} material={materials.barrel_bottom} />
    </group>
  )
}

useGLTF.preload('/chunk100--200-lvl-1-transformed.glb')
