/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.2 ./maps/chunk0--25-lvl-1.glb --transform --resolution --shadows -o ./maps/chunk0--25-lvl-1-transformed.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/chunk0--25-lvl-1-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Andesite.geometry} material={materials.andesite} />
      <mesh castShadow receiveShadow geometry={nodes.Jungle_Wood_Planks.geometry} material={materials.jungle_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Bedrock.geometry} material={materials.bedrock} />
      <mesh castShadow receiveShadow geometry={nodes.Oak_Leaves.geometry} material={materials.oak_leaves} />
      <mesh castShadow receiveShadow geometry={nodes.Grass.geometry} material={materials.grass} />
      <mesh castShadow receiveShadow geometry={nodes.Piston.geometry} material={materials.piston_side} />
      <mesh castShadow receiveShadow geometry={nodes.Allium.geometry} material={materials.allium} />
      <mesh castShadow receiveShadow geometry={nodes.Mossy_Cobblestone.geometry} material={materials.mossy_cobblestone} />
      <mesh castShadow receiveShadow geometry={nodes.Mossy_Stone_Bricks.geometry} material={materials.mossy_stone_bricks} />
      <mesh castShadow receiveShadow geometry={nodes.Brown_Mushroom_Block.geometry} material={materials.brown_mushroom_block} />
      <mesh castShadow receiveShadow geometry={nodes.Double_Jungle_Slab.geometry} material={materials.jungle_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Jungle_Slab.geometry} material={materials.jungle_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Jungle_Stairs.geometry} material={materials.jungle_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Mossy_Cobblestone_Wall.geometry} material={materials.mossy_cobblestone} />
      <mesh castShadow receiveShadow geometry={nodes.Potato.geometry} material={materials.potatoes_stage3} />
      <mesh castShadow receiveShadow geometry={nodes.Cyan_Terracotta.geometry} material={materials.cyan_terracotta} />
      <mesh castShadow receiveShadow geometry={nodes.Acacia_Wood.geometry} material={materials.acacia_log} />
      <mesh castShadow receiveShadow geometry={nodes.Cyan_Carpet.geometry} material={materials.cyan_wool} />
      <mesh castShadow receiveShadow geometry={nodes.Jungle_Fence_Gate.geometry} material={materials.jungle_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Jungle_Fence.geometry} material={materials.jungle_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Mossy_Stone_Brick_Slab.geometry} material={materials.mossy_stone_bricks} />
      <mesh castShadow receiveShadow geometry={nodes.Mossy_Stone_Brick_Slab_1.geometry} material={materials.mossy_stone_bricks} />
      <mesh castShadow receiveShadow geometry={nodes.Jungle_Trapdoor.geometry} material={materials.jungle_trapdoor} />
      <mesh castShadow receiveShadow geometry={nodes.Jungle_Button.geometry} material={materials.jungle_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Cyan_Wall_Banner.geometry} material={materials.cyan_concrete} />
      <mesh castShadow receiveShadow geometry={nodes.Smooth_Stone.geometry} material={materials.smooth_stone} />
      <mesh castShadow receiveShadow geometry={nodes.Mossy_Stone_Brick_Stairs.geometry} material={materials.mossy_stone_bricks} />
      <mesh castShadow receiveShadow geometry={nodes.Mossy_Cobblestone_Stairs.geometry} material={materials.mossy_cobblestone} />
      <mesh castShadow receiveShadow geometry={nodes.Tuff.geometry} material={materials.tuff} />
      <mesh castShadow receiveShadow geometry={nodes.Waxed_Oxidized_Cut_Copper.geometry} material={materials.oxidized_cut_copper} />
      <mesh castShadow receiveShadow geometry={nodes.Moss_Block.geometry} material={materials.moss_block} />
      <mesh castShadow receiveShadow geometry={nodes.Double_Waxed_Oxidized_Cut_Copper_Slab.geometry} material={materials.oxidized_cut_copper} />
      <mesh castShadow receiveShadow geometry={nodes.Waxed_Oxidized_Cut_Copper_Slab.geometry} material={materials.oxidized_cut_copper} />
      <mesh castShadow receiveShadow geometry={nodes.Waxed_Oxidized_Cut_Copper_Stairs.geometry} material={materials.oxidized_cut_copper} />
      <mesh castShadow receiveShadow geometry={nodes.Lilac_1.geometry} material={materials.lilac_bottom} />
      <mesh castShadow receiveShadow geometry={nodes.Lilac_2.geometry} material={materials.lilac_top} />
      <mesh castShadow receiveShadow geometry={nodes.Large_Fern_1.geometry} material={materials.large_fern_bottom} />
      <mesh castShadow receiveShadow geometry={nodes.Large_Fern_2.geometry} material={materials.large_fern_top} />
      <mesh castShadow receiveShadow geometry={nodes.Bamboo_1.geometry} material={materials.bamboo_large_leaves} />
      <mesh castShadow receiveShadow geometry={nodes.Bamboo_2.geometry} material={materials.bamboo_small_leaves} />
      <mesh castShadow receiveShadow geometry={nodes.Bamboo_3.geometry} material={materials.bamboo_stalk} />
    </group>
  )
}

useGLTF.preload('/chunk0--25-lvl-1-transformed.glb')
