/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.2 ./maps/chunk100--250-lvl-1.glb --transform --resolution --shadows -o ./maps/chunk100--250-lvl-1-transformed.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/chunk100--250-lvl-1-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Stone.geometry} material={materials.stone} />
      <mesh castShadow receiveShadow geometry={nodes.Granite.geometry} material={materials.granite} />
      <mesh castShadow receiveShadow geometry={nodes.Andesite.geometry} material={materials.andesite} />
      <mesh castShadow receiveShadow geometry={nodes.Polished_Andesite.geometry} material={materials.polished_andesite} />
      <mesh castShadow receiveShadow geometry={nodes.Dark_Oak_Wood_Planks.geometry} material={materials.dark_oak_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Bedrock.geometry} material={materials.bedrock} />
      <mesh castShadow receiveShadow geometry={nodes.Iron_Ore.geometry} material={materials.iron_ore} />
      <mesh castShadow receiveShadow geometry={nodes.Oak_Wood.geometry} material={materials.oak_log} />
      <mesh castShadow receiveShadow geometry={nodes.Spruce_Wood.geometry} material={materials.spruce_log} />
      <mesh castShadow receiveShadow geometry={nodes.Birch_Leaves.geometry} material={materials.birch_leaves} />
      <mesh castShadow receiveShadow geometry={nodes.Jungle_Leaves.geometry} material={materials.jungle_leaves} />
      <mesh castShadow receiveShadow geometry={nodes.Grass.geometry} material={materials.grass} />
      <mesh castShadow receiveShadow geometry={nodes.Gray_Wool.geometry} material={materials.gray_wool} />
      <mesh castShadow receiveShadow geometry={nodes.Brown_Wool.geometry} material={materials.brown_wool} />
      <mesh castShadow receiveShadow geometry={nodes.Allium.geometry} material={materials.allium} />
      <mesh castShadow receiveShadow geometry={nodes.Azure_Bluet.geometry} material={materials.azure_bluet} />
      <mesh castShadow receiveShadow geometry={nodes.Stone_Brick_Slab.geometry} material={materials.stone_bricks} />
      <mesh castShadow receiveShadow geometry={nodes.Soul_Sand.geometry} material={materials.soul_sand} />
      <mesh castShadow receiveShadow geometry={nodes.Mossy_Stone_Bricks.geometry} material={materials.mossy_stone_bricks} />
      <mesh castShadow receiveShadow geometry={nodes.Stone_Brick_Stairs.geometry} material={materials.stone_bricks} />
      <mesh castShadow receiveShadow geometry={nodes.Nether_Brick.geometry} material={materials.nether_bricks} />
      <mesh castShadow receiveShadow geometry={nodes.Double_Spruce_Slab.geometry} material={materials.spruce_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Spruce_Slab.geometry} material={materials.spruce_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Cyan_Terracotta.geometry} material={materials.cyan_terracotta} />
      <mesh castShadow receiveShadow geometry={nodes.Dark_Oak_Wood.geometry} material={materials.dark_oak_log} />
      <mesh castShadow receiveShadow geometry={nodes.Light_Carpet.geometry} material={materials.light_gray_wool} />
      <mesh castShadow receiveShadow geometry={nodes.Spruce_Fence_Gate.geometry} material={materials.spruce_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Spruce_Fence.geometry} material={materials.spruce_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Gray_Concrete.geometry} material={materials.gray_concrete} />
      <mesh castShadow receiveShadow geometry={nodes.Brown_Concrete.geometry} material={materials.brown_concrete} />
      <mesh castShadow receiveShadow geometry={nodes.Spruce_Trapdoor.geometry} material={materials.spruce_trapdoor} />
      <mesh castShadow receiveShadow geometry={nodes.Stripped_Spruce_Wood.geometry} material={materials.stripped_spruce_log} />
      <mesh castShadow receiveShadow geometry={nodes.Chain.geometry} material={materials.chain} />
      <mesh castShadow receiveShadow geometry={nodes.Stone_Stairs.geometry} material={materials.stone} />
      <mesh castShadow receiveShadow geometry={nodes.Polished_Andesite_Stairs.geometry} material={materials.polished_andesite} />
      <mesh castShadow receiveShadow geometry={nodes.Block_of_Amethyst.geometry} material={materials.amethyst_block} />
      <mesh castShadow receiveShadow geometry={nodes.Tuff.geometry} material={materials.tuff} />
      <mesh castShadow receiveShadow geometry={nodes.Dripstone_Block.geometry} material={materials.dripstone_block} />
      <mesh castShadow receiveShadow geometry={nodes.Copper_Ore.geometry} material={materials.copper_ore} />
      <mesh castShadow receiveShadow geometry={nodes.Moss_Block.geometry} material={materials.moss_block} />
      <mesh castShadow receiveShadow geometry={nodes.Oak_Log_1.geometry} material={materials.oak_log} />
      <mesh castShadow receiveShadow geometry={nodes.Oak_Log_2.geometry} material={materials.oak_log_top} />
      <mesh castShadow receiveShadow geometry={nodes.Loom_1.geometry} material={materials.loom_top} />
      <mesh castShadow receiveShadow geometry={nodes.Loom_2.geometry} material={materials.loom_side} />
      <mesh castShadow receiveShadow geometry={nodes.Loom_3.geometry} material={materials.loom_bottom} />
      <mesh castShadow receiveShadow geometry={nodes.Loom_4.geometry} material={materials.loom_front} />
      <mesh castShadow receiveShadow geometry={nodes.Lilac_1.geometry} material={materials.lilac_bottom} />
      <mesh castShadow receiveShadow geometry={nodes.Lilac_2.geometry} material={materials.lilac_top} />
      <mesh castShadow receiveShadow geometry={nodes.Large_Fern_1.geometry} material={materials.large_fern_bottom} />
      <mesh castShadow receiveShadow geometry={nodes.Large_Fern_2.geometry} material={materials.large_fern_top} />
      <mesh castShadow receiveShadow geometry={nodes.Composter_1.geometry} material={materials.composter_top} />
      <mesh castShadow receiveShadow geometry={nodes.Composter_2.geometry} material={materials.composter_side} />
      <mesh castShadow receiveShadow geometry={nodes.Composter_3.geometry} material={materials.composter_bottom} />
      <mesh castShadow receiveShadow geometry={nodes.Barrel_1.geometry} material={materials.barrel_top} />
      <mesh castShadow receiveShadow geometry={nodes.Barrel_2.geometry} material={materials.barrel_side} />
      <mesh castShadow receiveShadow geometry={nodes.Barrel_3.geometry} material={materials.barrel_bottom} />
      <mesh castShadow receiveShadow geometry={nodes.Beehive_1.geometry} material={materials.beehive_end} />
      <mesh castShadow receiveShadow geometry={nodes.Beehive_2.geometry} material={materials.beehive_front} />
      <mesh castShadow receiveShadow geometry={nodes.Beehive_3.geometry} material={materials.beehive_side} />
    </group>
  )
}

useGLTF.preload('/chunk100--250-lvl-1-transformed.glb')
