/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.2 ./maps/chunk175--125-lvl-1.glb --transform --resolution --shadows -o ./maps/chunk175--125-lvl-1-transformed.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/chunk175--125-lvl-1-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Dark_Oak_Wood_Planks.geometry} material={materials.dark_oak_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Bedrock.geometry} material={materials.bedrock} />
      <mesh castShadow receiveShadow geometry={nodes.Sand.geometry} material={materials.sand} />
      <mesh castShadow receiveShadow geometry={nodes.Spruce_Wood.geometry} material={materials.spruce_log} />
      <mesh castShadow receiveShadow geometry={nodes.Oak_Leaves.geometry} material={materials.oak_leaves} />
      <mesh castShadow receiveShadow geometry={nodes.Birch_Leaves.geometry} material={materials.birch_leaves} />
      <mesh castShadow receiveShadow geometry={nodes.Jungle_Leaves.geometry} material={materials.jungle_leaves} />
      <mesh castShadow receiveShadow geometry={nodes.Grass.geometry} material={materials.grass} />
      <mesh castShadow receiveShadow geometry={nodes.Allium.geometry} material={materials.allium} />
      <mesh castShadow receiveShadow geometry={nodes.Azure_Bluet.geometry} material={materials.azure_bluet} />
      <mesh castShadow receiveShadow geometry={nodes.Clay.geometry} material={materials.clay} />
      <mesh castShadow receiveShadow geometry={nodes.Soul_Sand.geometry} material={materials.soul_sand} />
      <mesh castShadow receiveShadow geometry={nodes.Mossy_Stone_Bricks.geometry} material={materials.mossy_stone_bricks} />
      <mesh castShadow receiveShadow geometry={nodes.Nether_Brick.geometry} material={materials.nether_bricks} />
      <mesh castShadow receiveShadow geometry={nodes.Potato.geometry} material={materials.potatoes_stage3} />
      <mesh castShadow receiveShadow geometry={nodes.Cyan_Terracotta.geometry} material={materials.cyan_terracotta} />
      <mesh castShadow receiveShadow geometry={nodes.Dark_Oak_Wood.geometry} material={materials.dark_oak_log} />
      <mesh castShadow receiveShadow geometry={nodes.Moss_Carpet.geometry} material={materials.moss_block} />
      <mesh castShadow receiveShadow geometry={nodes.Spruce_Fence.geometry} material={materials.spruce_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Seagrass.geometry} material={materials.tall_seagrass_top} />
      <mesh castShadow receiveShadow geometry={nodes.Tuff.geometry} material={materials.tuff} />
      <mesh castShadow receiveShadow geometry={nodes.Moss_Block.geometry} material={materials.moss_block} />
      <mesh castShadow receiveShadow geometry={nodes.Stationary_Water_1.geometry} material={materials.water_still} />
      <mesh castShadow receiveShadow geometry={nodes.Stationary_Water_2.geometry} material={materials.water_flow} />
      <mesh castShadow receiveShadow geometry={nodes.Lilac_1.geometry} material={materials.lilac_bottom} />
      <mesh castShadow receiveShadow geometry={nodes.Lilac_2.geometry} material={materials.lilac_top} />
      <mesh castShadow receiveShadow geometry={nodes.Double_Tallgrass_1.geometry} material={materials.tall_grass_bottom} />
      <mesh castShadow receiveShadow geometry={nodes.Double_Tallgrass_2.geometry} material={materials.tall_grass_top} />
      <mesh castShadow receiveShadow geometry={nodes.Large_Fern_1.geometry} material={materials.large_fern_bottom} />
      <mesh castShadow receiveShadow geometry={nodes.Large_Fern_2.geometry} material={materials.large_fern_top} />
      <mesh castShadow receiveShadow geometry={nodes.Bamboo_1.geometry} material={materials.bamboo_large_leaves} />
      <mesh castShadow receiveShadow geometry={nodes.Bamboo_2.geometry} material={materials.bamboo_small_leaves} />
      <mesh castShadow receiveShadow geometry={nodes.Bamboo_3.geometry} material={materials.bamboo_stalk} />
      <mesh castShadow receiveShadow geometry={nodes.Flowering_Azalea_1.geometry} material={materials.flowering_azalea_top} />
      <mesh castShadow receiveShadow geometry={nodes.Flowering_Azalea_2.geometry} material={materials.flowering_azalea_side} />
      <mesh castShadow receiveShadow geometry={nodes.Flowering_Azalea_3.geometry} material={materials.azalea_plant} />
    </group>
  )
}

useGLTF.preload('/chunk175--125-lvl-1-transformed.glb')
