/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.2 ./maps/chunk100--175-lvl-1.glb --transform --resolution --shadows -o ./maps/chunk100--175-lvl-1-transformed.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/chunk100--175-lvl-1-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Stone.geometry} material={materials.stone} />
      <mesh castShadow receiveShadow geometry={nodes.Granite.geometry} material={materials.granite} />
      <mesh castShadow receiveShadow geometry={nodes.Andesite.geometry} material={materials.andesite} />
      <mesh castShadow receiveShadow geometry={nodes.Polished_Andesite.geometry} material={materials.polished_andesite} />
      <mesh castShadow receiveShadow geometry={nodes.Nether_Gold_Ore.geometry} material={materials.nether_gold_ore} />
      <mesh castShadow receiveShadow geometry={nodes.Grass_Block.geometry} material={materials.grass_block_top} />
      <mesh castShadow receiveShadow geometry={nodes.Dirt.geometry} material={materials.dirt} />
      <mesh castShadow receiveShadow geometry={nodes.Coarse_Dirt.geometry} material={materials.coarse_dirt} />
      <mesh castShadow receiveShadow geometry={nodes.Jungle_Wood_Planks.geometry} material={materials.jungle_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Dark_Oak_Wood_Planks.geometry} material={materials.dark_oak_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Bedrock.geometry} material={materials.bedrock} />
      <mesh castShadow receiveShadow geometry={nodes.Stationary_Water.geometry} material={materials.water_still} />
      <mesh castShadow receiveShadow geometry={nodes.Iron_Ore.geometry} material={materials.iron_ore} />
      <mesh castShadow receiveShadow geometry={nodes.Birch_Leaves.geometry} material={materials.birch_leaves} />
      <mesh castShadow receiveShadow geometry={nodes.Jungle_Leaves.geometry} material={materials.jungle_leaves} />
      <mesh castShadow receiveShadow geometry={nodes.Glass.geometry} material={materials.glass} />
      <mesh castShadow receiveShadow geometry={nodes.Grass.geometry} material={materials.grass} />
      <mesh castShadow receiveShadow geometry={nodes.Cyan_Wool.geometry} material={materials.cyan_wool} />
      <mesh castShadow receiveShadow geometry={nodes.Azure_Bluet.geometry} material={materials.azure_bluet} />
      <mesh castShadow receiveShadow geometry={nodes.Brown_Mushroom.geometry} material={materials.brown_mushroom} />
      <mesh castShadow receiveShadow geometry={nodes.Block_of_Iron.geometry} material={materials.iron_block} />
      <mesh castShadow receiveShadow geometry={nodes.Cobblestone_Slab.geometry} material={materials.cobblestone} />
      <mesh castShadow receiveShadow geometry={nodes.Stone_Brick_Slab.geometry} material={materials.stone_bricks} />
      <mesh castShadow receiveShadow geometry={nodes.Mossy_Cobblestone.geometry} material={materials.mossy_cobblestone} />
      <mesh castShadow receiveShadow geometry={nodes.Obsidian.geometry} material={materials.obsidian} />
      <mesh castShadow receiveShadow geometry={nodes.Cobblestone_Stairs.geometry} material={materials.cobblestone} />
      <mesh castShadow receiveShadow geometry={nodes.Fence.geometry} material={materials.oak_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Brown_Stained_Glass.geometry} material={materials.brown_stained_glass} />
      <mesh castShadow receiveShadow geometry={nodes.Oak_Trapdoor.geometry} material={materials.oak_trapdoor} />
      <mesh castShadow receiveShadow geometry={nodes.Mossy_Stone_Bricks.geometry} material={materials.mossy_stone_bricks} />
      <mesh castShadow receiveShadow geometry={nodes.Stone_Brick_Stairs.geometry} material={materials.stone_bricks} />
      <mesh castShadow receiveShadow geometry={nodes['Redstone_Lamp_(inactive)'].geometry} material={materials.redstone_lamp} />
      <mesh castShadow receiveShadow geometry={nodes.Double_Spruce_Slab.geometry} material={materials.spruce_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Oak_Slab.geometry} material={materials.oak_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Spruce_Slab.geometry} material={materials.spruce_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Jungle_Slab.geometry} material={materials.jungle_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Dark_Oak_Slab.geometry} material={materials.dark_oak_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Spruce_Stairs.geometry} material={materials.spruce_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Jungle_Stairs.geometry} material={materials.jungle_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Beacon.geometry} material={materials.beacon} />
      <mesh castShadow receiveShadow geometry={nodes.Cobblestone_Wall.geometry} material={materials.cobblestone} />
      <mesh castShadow receiveShadow geometry={nodes.Stone_Brick_Wall.geometry} material={materials.stone_bricks} />
      <mesh castShadow receiveShadow geometry={nodes.Mossy_Stone_Brick_Wall.geometry} material={materials.mossy_stone_bricks} />
      <mesh castShadow receiveShadow geometry={nodes.Black_Terracotta.geometry} material={materials.black_terracotta} />
      <mesh castShadow receiveShadow geometry={nodes.Dark_Oak_Stairs.geometry} material={materials.dark_oak_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Light_Carpet.geometry} material={materials.light_gray_wool} />
      <mesh castShadow receiveShadow geometry={nodes.Cyan_Carpet.geometry} material={materials.cyan_wool} />
      <mesh castShadow receiveShadow geometry={nodes.Moss_Carpet.geometry} material={materials.moss_block} />
      <mesh castShadow receiveShadow geometry={nodes.Block_of_Coal.geometry} material={materials.coal_block} />
      <mesh castShadow receiveShadow geometry={nodes.Jungle_Fence_Gate.geometry} material={materials.jungle_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Spruce_Fence.geometry} material={materials.spruce_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Dark_Oak_Fence.geometry} material={materials.dark_oak_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Black_Concrete.geometry} material={materials.black_concrete} />
      <mesh castShadow receiveShadow geometry={nodes.Stripped_Jungle_Wood.geometry} material={materials.stripped_jungle_log} />
      <mesh castShadow receiveShadow geometry={nodes.Stone_Slab.geometry} material={materials.stone} />
      <mesh castShadow receiveShadow geometry={nodes.Lantern.geometry} material={materials.lantern} />
      <mesh castShadow receiveShadow geometry={nodes.Chain.geometry} material={materials.chain} />
      <mesh castShadow receiveShadow geometry={nodes.Stone_Stairs.geometry} material={materials.stone} />
      <mesh castShadow receiveShadow geometry={nodes.Polished_Andesite_Stairs.geometry} material={materials.polished_andesite} />
      <mesh castShadow receiveShadow geometry={nodes.Waxed_Oxidized_Cut_Copper.geometry} material={materials.oxidized_cut_copper} />
      <mesh castShadow receiveShadow geometry={nodes.Moss_Block.geometry} material={materials.moss_block} />
      <mesh castShadow receiveShadow geometry={nodes.Waxed_Oxidized_Cut_Copper_Slab.geometry} material={materials.oxidized_cut_copper} />
      <mesh castShadow receiveShadow geometry={nodes.Spruce_Log_1.geometry} material={materials.spruce_log} />
      <mesh castShadow receiveShadow geometry={nodes.Spruce_Log_2.geometry} material={materials.spruce_log_top} />
      <mesh castShadow receiveShadow geometry={nodes.Bookshelf_1.geometry} material={materials.oak_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Bookshelf_2.geometry} material={materials.bookshelf} />
      <mesh castShadow receiveShadow geometry={nodes.Chest_1.geometry} material={materials.MWO_chest_top} />
      <mesh castShadow receiveShadow geometry={nodes.Chest_2.geometry} material={materials.MWO_chest_side} />
      <mesh castShadow receiveShadow geometry={nodes.Chest_3.geometry} material={materials.MWO_chest_front} />
      <mesh castShadow receiveShadow geometry={nodes.Chest_4.geometry} material={materials.MWO_double_chest_front_left} />
      <mesh castShadow receiveShadow geometry={nodes.Chest_5.geometry} material={materials.MWO_double_chest_front_right} />
      <mesh castShadow receiveShadow geometry={nodes.Chest_6.geometry} material={materials.MWO_double_chest_back_left} />
      <mesh castShadow receiveShadow geometry={nodes.Chest_7.geometry} material={materials.MWO_double_chest_back_right} />
      <mesh castShadow receiveShadow geometry={nodes.Chest_8.geometry} material={materials.MWO_double_chest_top_left} />
      <mesh castShadow receiveShadow geometry={nodes.Chest_9.geometry} material={materials.MWO_double_chest_top_right} />
      <mesh castShadow receiveShadow geometry={nodes.Chest_10.geometry} material={materials.MWO_chest_latch} />
      <mesh castShadow receiveShadow geometry={nodes.Crafting_Table_1.geometry} material={materials.oak_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Crafting_Table_2.geometry} material={materials.crafting_table_front} />
      <mesh castShadow receiveShadow geometry={nodes.Loom_1.geometry} material={materials.loom_top} />
      <mesh castShadow receiveShadow geometry={nodes.Loom_2.geometry} material={materials.loom_side} />
      <mesh castShadow receiveShadow geometry={nodes.Loom_3.geometry} material={materials.loom_bottom} />
      <mesh castShadow receiveShadow geometry={nodes.Loom_4.geometry} material={materials.loom_front} />
      <mesh castShadow receiveShadow geometry={nodes.Enchanting_Table_1.geometry} material={materials.enchanting_table_top} />
      <mesh castShadow receiveShadow geometry={nodes.Enchanting_Table_2.geometry} material={materials.enchanting_table_side} />
      <mesh castShadow receiveShadow geometry={nodes.Enchanting_Table_3.geometry} material={materials.enchanting_table_bottom} />
      <mesh castShadow receiveShadow geometry={nodes.Skeleton_Skull_1.geometry} material={materials.pumpkin_top} />
      <mesh castShadow receiveShadow geometry={nodes.Skeleton_Skull_2.geometry} material={materials.pumpkin_side} />
      <mesh castShadow receiveShadow geometry={nodes.Skeleton_Skull_3.geometry} material={materials.carved_pumpkin} />
      <mesh castShadow receiveShadow geometry={nodes.Brown_Stained_Glass_Pane_1.geometry} material={materials.brown_stained_glass} />
      <mesh castShadow receiveShadow geometry={nodes.Brown_Stained_Glass_Pane_2.geometry} material={materials.brown_stained_glass_pane_top} />
      <mesh castShadow receiveShadow geometry={nodes.Bamboo_1.geometry} material={materials.bamboo_large_leaves} />
      <mesh castShadow receiveShadow geometry={nodes.Bamboo_2.geometry} material={materials.bamboo_small_leaves} />
      <mesh castShadow receiveShadow geometry={nodes.Bamboo_3.geometry} material={materials.bamboo_stalk} />
      <mesh castShadow receiveShadow geometry={nodes.Composter_1.geometry} material={materials.composter_top} />
      <mesh castShadow receiveShadow geometry={nodes.Composter_2.geometry} material={materials.composter_side} />
      <mesh castShadow receiveShadow geometry={nodes.Composter_3.geometry} material={materials.composter_bottom} />
      <mesh castShadow receiveShadow geometry={nodes.Barrel_1.geometry} material={materials.barrel_top} />
      <mesh castShadow receiveShadow geometry={nodes.Barrel_2.geometry} material={materials.barrel_side} />
      <mesh castShadow receiveShadow geometry={nodes.Barrel_3.geometry} material={materials.barrel_bottom} />
      <mesh castShadow receiveShadow geometry={nodes.Bee_Nest_1.geometry} material={materials.bee_nest_bottom} />
      <mesh castShadow receiveShadow geometry={nodes.Bee_Nest_2.geometry} material={materials.bee_nest_front} />
      <mesh castShadow receiveShadow geometry={nodes.Bee_Nest_3.geometry} material={materials.bee_nest_side} />
      <mesh castShadow receiveShadow geometry={nodes.Bee_Nest_4.geometry} material={materials.bee_nest_top} />
      <mesh castShadow receiveShadow geometry={nodes.Beehive_1.geometry} material={materials.beehive_end} />
      <mesh castShadow receiveShadow geometry={nodes.Beehive_2.geometry} material={materials.beehive_front} />
      <mesh castShadow receiveShadow geometry={nodes.Beehive_3.geometry} material={materials.beehive_side} />
    </group>
  )
}

useGLTF.preload('/chunk100--175-lvl-1-transformed.glb')
