/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.2 ./maps/chunk50--250-lvl-1.glb --transform --resolution --shadows -o ./maps/chunk50--250-lvl-1-transformed.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/chunk50--250-lvl-1-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Stone.geometry} material={materials.stone} />
      <mesh castShadow receiveShadow geometry={nodes.Andesite.geometry} material={materials.andesite} />
      <mesh castShadow receiveShadow geometry={nodes.Polished_Andesite.geometry} material={materials.polished_andesite} />
      <mesh castShadow receiveShadow geometry={nodes.Coarse_Dirt.geometry} material={materials.coarse_dirt} />
      <mesh castShadow receiveShadow geometry={nodes.Jungle_Wood_Planks.geometry} material={materials.jungle_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Dark_Oak_Wood_Planks.geometry} material={materials.dark_oak_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Bedrock.geometry} material={materials.bedrock} />
      <mesh castShadow receiveShadow geometry={nodes.Stationary_Water.geometry} material={materials.water_still} />
      <mesh castShadow receiveShadow geometry={nodes.Oak_Leaves.geometry} material={materials.oak_leaves} />
      <mesh castShadow receiveShadow geometry={nodes.Jungle_Leaves.geometry} material={materials.jungle_leaves} />
      <mesh castShadow receiveShadow geometry={nodes.Grass.geometry} material={materials.grass} />
      <mesh castShadow receiveShadow geometry={nodes.Dead_Bush.geometry} material={materials.dead_bush} />
      <mesh castShadow receiveShadow geometry={nodes.Allium.geometry} material={materials.allium} />
      <mesh castShadow receiveShadow geometry={nodes.Brown_Mushroom.geometry} material={materials.brown_mushroom} />
      <mesh castShadow receiveShadow geometry={nodes.Red_Mushroom.geometry} material={materials.red_mushroom} />
      <mesh castShadow receiveShadow geometry={nodes.Stone_Brick_Slab.geometry} material={materials.stone_bricks} />
      <mesh castShadow receiveShadow geometry={nodes.Mossy_Stone_Bricks.geometry} material={materials.mossy_stone_bricks} />
      <mesh castShadow receiveShadow geometry={nodes.Stone_Brick_Stairs.geometry} material={materials.stone_bricks} />
      <mesh castShadow receiveShadow geometry={nodes.Double_Spruce_Slab.geometry} material={materials.spruce_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Double_Jungle_Slab.geometry} material={materials.jungle_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Spruce_Slab.geometry} material={materials.spruce_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Jungle_Slab.geometry} material={materials.jungle_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Potato.geometry} material={materials.potatoes_stage3} />
      <mesh castShadow receiveShadow geometry={nodes.Light_Carpet.geometry} material={materials.light_gray_wool} />
      <mesh castShadow receiveShadow geometry={nodes.Spruce_Fence.geometry} material={materials.spruce_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Stripped_Jungle_Wood.geometry} material={materials.stripped_jungle_log} />
      <mesh castShadow receiveShadow geometry={nodes.Chain.geometry} material={materials.chain} />
      <mesh castShadow receiveShadow geometry={nodes.Stone_Stairs.geometry} material={materials.stone} />
      <mesh castShadow receiveShadow geometry={nodes.Polished_Andesite_Stairs.geometry} material={materials.polished_andesite} />
      <mesh castShadow receiveShadow geometry={nodes.Block_of_Amethyst.geometry} material={materials.amethyst_block} />
      <mesh castShadow receiveShadow geometry={nodes.Copper_Ore.geometry} material={materials.copper_ore} />
      <mesh castShadow receiveShadow geometry={nodes.Moss_Block.geometry} material={materials.moss_block} />
      <mesh castShadow receiveShadow geometry={nodes.Mangrove_Planks.geometry} material={materials.mangrove_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Mangrove_Leaves.geometry} material={materials.mangrove_leaves} />
      <mesh castShadow receiveShadow geometry={nodes.Podzol_1.geometry} material={materials.podzol_side} />
      <mesh castShadow receiveShadow geometry={nodes.Podzol_2.geometry} material={materials.podzol_top} />
      <mesh castShadow receiveShadow geometry={nodes.Bookshelf_1.geometry} material={materials.oak_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Bookshelf_2.geometry} material={materials.bookshelf} />
      <mesh castShadow receiveShadow geometry={nodes.Chest_1.geometry} material={materials.MWO_chest_top} />
      <mesh castShadow receiveShadow geometry={nodes.Chest_2.geometry} material={materials.MWO_chest_side} />
      <mesh castShadow receiveShadow geometry={nodes.Chest_3.geometry} material={materials.MWO_chest_front} />
      <mesh castShadow receiveShadow geometry={nodes.Chest_4.geometry} material={materials.MWO_chest_latch} />
      <mesh castShadow receiveShadow geometry={nodes.Crafting_Table_1.geometry} material={materials.oak_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Crafting_Table_2.geometry} material={materials.crafting_table_top} />
      <mesh castShadow receiveShadow geometry={nodes.Crafting_Table_3.geometry} material={materials.crafting_table_side} />
      <mesh castShadow receiveShadow geometry={nodes.Crafting_Table_4.geometry} material={materials.crafting_table_front} />
      <mesh castShadow receiveShadow geometry={nodes.Green_Stained_Glass_Pane_1.geometry} material={materials.green_stained_glass} />
      <mesh castShadow receiveShadow geometry={nodes.Green_Stained_Glass_Pane_2.geometry} material={materials.green_stained_glass_pane_top} />
      <mesh castShadow receiveShadow geometry={nodes.Large_Fern_1.geometry} material={materials.large_fern_bottom} />
      <mesh castShadow receiveShadow geometry={nodes.Large_Fern_2.geometry} material={materials.large_fern_top} />
      <mesh castShadow receiveShadow geometry={nodes.Bamboo_1.geometry} material={materials.bamboo_large_leaves} />
      <mesh castShadow receiveShadow geometry={nodes.Bamboo_2.geometry} material={materials.bamboo_small_leaves} />
      <mesh castShadow receiveShadow geometry={nodes.Bamboo_3.geometry} material={materials.bamboo_stalk} />
      <mesh castShadow receiveShadow geometry={nodes.Composter_1.geometry} material={materials.composter_top} />
      <mesh castShadow receiveShadow geometry={nodes.Composter_2.geometry} material={materials.composter_side} />
      <mesh castShadow receiveShadow geometry={nodes.Composter_3.geometry} material={materials.composter_bottom} />
      <mesh castShadow receiveShadow geometry={nodes.Barrel_1.geometry} material={materials.barrel_top} />
      <mesh castShadow receiveShadow geometry={nodes.Barrel_2.geometry} material={materials.barrel_side} />
      <mesh castShadow receiveShadow geometry={nodes.Barrel_3.geometry} material={materials.barrel_bottom} />
      <mesh castShadow receiveShadow geometry={nodes.Bee_Nest_1.geometry} material={materials.bee_nest_bottom} />
      <mesh castShadow receiveShadow geometry={nodes.Bee_Nest_2.geometry} material={materials.bee_nest_front} />
      <mesh castShadow receiveShadow geometry={nodes.Bee_Nest_3.geometry} material={materials.bee_nest_side} />
      <mesh castShadow receiveShadow geometry={nodes.Bee_Nest_4.geometry} material={materials.bee_nest_top} />
      <mesh castShadow receiveShadow geometry={nodes.Beehive_1.geometry} material={materials.beehive_end} />
      <mesh castShadow receiveShadow geometry={nodes.Beehive_2.geometry} material={materials.beehive_front} />
      <mesh castShadow receiveShadow geometry={nodes.Beehive_3.geometry} material={materials.beehive_side} />
    </group>
  )
}

useGLTF.preload('/chunk50--250-lvl-1-transformed.glb')
