/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.2 ./maps/chunk-100--75-lvl-1.glb --transform --resolution --shadows -o ./maps/chunk-100--75-lvl-1-transformed.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/chunk-100--75-lvl-1-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Stone.geometry} material={materials.stone} />
      <mesh castShadow receiveShadow geometry={nodes.Coarse_Dirt.geometry} material={materials.coarse_dirt} />
      <mesh castShadow receiveShadow geometry={nodes.Spruce_Wood_Planks.geometry} material={materials.spruce_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Dark_Oak_Wood_Planks.geometry} material={materials.dark_oak_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Bedrock.geometry} material={materials.bedrock} />
      <mesh castShadow receiveShadow geometry={nodes.Sand.geometry} material={materials.sand} />
      <mesh castShadow receiveShadow geometry={nodes.Jungle_Wood.geometry} material={materials.jungle_log} />
      <mesh castShadow receiveShadow geometry={nodes.Jungle_Leaves.geometry} material={materials.jungle_leaves} />
      <mesh castShadow receiveShadow geometry={nodes.Note_Block.geometry} material={materials.note_block} />
      <mesh castShadow receiveShadow geometry={nodes.Grass.geometry} material={materials.grass} />
      <mesh castShadow receiveShadow geometry={nodes.Piston.geometry} material={materials.piston_side} />
      <mesh castShadow receiveShadow geometry={nodes.Light_Wool.geometry} material={materials.light_blue_wool} />
      <mesh castShadow receiveShadow geometry={nodes.Brown_Wool.geometry} material={materials.brown_wool} />
      <mesh castShadow receiveShadow geometry={nodes.Blue_Orchid.geometry} material={materials.blue_orchid} />
      <mesh castShadow receiveShadow geometry={nodes.Allium.geometry} material={materials.allium} />
      <mesh castShadow receiveShadow geometry={nodes.Oxeye_Daisy.geometry} material={materials.oxeye_daisy} />
      <mesh castShadow receiveShadow geometry={nodes.Spruce_Wall_Sign.geometry} material={materials.spruce_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Sugar_Cane.geometry} material={materials.sugar_cane} />
      <mesh castShadow receiveShadow geometry={nodes.Mossy_Stone_Bricks.geometry} material={materials.mossy_stone_bricks} />
      <mesh castShadow receiveShadow geometry={nodes.Double_Jungle_Slab.geometry} material={materials.jungle_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Spruce_Slab.geometry} material={materials.spruce_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Jungle_Slab.geometry} material={materials.jungle_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Jungle_Stairs.geometry} material={materials.jungle_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Mossy_Cobblestone_Wall.geometry} material={materials.mossy_cobblestone} />
      <mesh castShadow receiveShadow geometry={nodes.Mossy_Stone_Brick_Wall.geometry} material={materials.mossy_stone_bricks} />
      <mesh castShadow receiveShadow geometry={nodes.Potato.geometry} material={materials.potatoes_stage3} />
      <mesh castShadow receiveShadow geometry={nodes.Cyan_Carpet.geometry} material={materials.cyan_wool} />
      <mesh castShadow receiveShadow geometry={nodes.Moss_Carpet.geometry} material={materials.moss_block} />
      <mesh castShadow receiveShadow geometry={nodes.Jungle_Fence_Gate.geometry} material={materials.jungle_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Spruce_Fence.geometry} material={materials.spruce_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Mossy_Stone_Brick_Slab.geometry} material={materials.mossy_stone_bricks} />
      <mesh castShadow receiveShadow geometry={nodes.Mossy_Stone_Brick_Slab_1.geometry} material={materials.mossy_stone_bricks} />
      <mesh castShadow receiveShadow geometry={nodes.Brown_Concrete_Powder.geometry} material={materials.brown_concrete_powder} />
      <mesh castShadow receiveShadow geometry={nodes.Spruce_Trapdoor.geometry} material={materials.spruce_trapdoor} />
      <mesh castShadow receiveShadow geometry={nodes.Jungle_Trapdoor.geometry} material={materials.jungle_trapdoor} />
      <mesh castShadow receiveShadow geometry={nodes.Jungle_Button.geometry} material={materials.jungle_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Stripped_Spruce_Wood.geometry} material={materials.stripped_spruce_log} />
      <mesh castShadow receiveShadow geometry={nodes.Cyan_Wall_Banner.geometry} material={materials.cyan_concrete} />
      <mesh castShadow receiveShadow geometry={nodes.Seagrass.geometry} material={materials.tall_seagrass_top} />
      <mesh castShadow receiveShadow geometry={nodes.Lantern.geometry} material={materials.lantern} />
      <mesh castShadow receiveShadow geometry={nodes.Campfire.geometry} material={materials.campfire_log} />
      <mesh castShadow receiveShadow geometry={nodes.Stone_Stairs.geometry} material={materials.stone} />
      <mesh castShadow receiveShadow geometry={nodes.Mossy_Stone_Brick_Stairs.geometry} material={materials.mossy_stone_bricks} />
      <mesh castShadow receiveShadow geometry={nodes.Moss_Block.geometry} material={materials.moss_block} />
      <mesh castShadow receiveShadow geometry={nodes.Double_Waxed_Oxidized_Cut_Copper_Slab.geometry} material={materials.oxidized_cut_copper} />
      <mesh castShadow receiveShadow geometry={nodes.Mangrove_Leaves.geometry} material={materials.mangrove_leaves} />
      <mesh castShadow receiveShadow geometry={nodes.Stationary_Water_1.geometry} material={materials.water_still} />
      <mesh castShadow receiveShadow geometry={nodes.Stationary_Water_2.geometry} material={materials.water_flow} />
      <mesh castShadow receiveShadow geometry={nodes.Green_Stained_Glass_Pane_1.geometry} material={materials.green_stained_glass} />
      <mesh castShadow receiveShadow geometry={nodes.Green_Stained_Glass_Pane_2.geometry} material={materials.green_stained_glass_pane_top} />
      <mesh castShadow receiveShadow geometry={nodes.Double_Tallgrass_1.geometry} material={materials.tall_grass_bottom} />
      <mesh castShadow receiveShadow geometry={nodes.Double_Tallgrass_2.geometry} material={materials.tall_grass_top} />
      <mesh castShadow receiveShadow geometry={nodes.Large_Fern_1.geometry} material={materials.large_fern_bottom} />
      <mesh castShadow receiveShadow geometry={nodes.Large_Fern_2.geometry} material={materials.large_fern_top} />
      <mesh castShadow receiveShadow geometry={nodes.Rose_Bush_1.geometry} material={materials.rose_bush_bottom} />
      <mesh castShadow receiveShadow geometry={nodes.Rose_Bush_2.geometry} material={materials.rose_bush_top} />
      <mesh castShadow receiveShadow geometry={nodes.Peony_1.geometry} material={materials.peony_bottom} />
      <mesh castShadow receiveShadow geometry={nodes.Peony_2.geometry} material={materials.peony_top} />
      <mesh castShadow receiveShadow geometry={nodes.Bamboo_1.geometry} material={materials.bamboo_large_leaves} />
      <mesh castShadow receiveShadow geometry={nodes.Bamboo_2.geometry} material={materials.bamboo_small_leaves} />
      <mesh castShadow receiveShadow geometry={nodes.Bamboo_3.geometry} material={materials.bamboo_stalk} />
      <mesh castShadow receiveShadow geometry={nodes.Composter_1.geometry} material={materials.composter_top} />
      <mesh castShadow receiveShadow geometry={nodes.Composter_2.geometry} material={materials.composter_side} />
      <mesh castShadow receiveShadow geometry={nodes.Composter_3.geometry} material={materials.composter_bottom} />
      <mesh castShadow receiveShadow geometry={nodes.Barrel_1.geometry} material={materials.barrel_top} />
      <mesh castShadow receiveShadow geometry={nodes.Barrel_2.geometry} material={materials.barrel_side} />
      <mesh castShadow receiveShadow geometry={nodes.Grindstone_1.geometry} material={materials.dark_oak_log} />
      <mesh castShadow receiveShadow geometry={nodes.Grindstone_2.geometry} material={materials.grindstone_side} />
      <mesh castShadow receiveShadow geometry={nodes.Grindstone_3.geometry} material={materials.grindstone_pivot} />
      <mesh castShadow receiveShadow geometry={nodes.Grindstone_4.geometry} material={materials.grindstone_round} />
      <mesh castShadow receiveShadow geometry={nodes.Beehive_1.geometry} material={materials.beehive_end} />
      <mesh castShadow receiveShadow geometry={nodes.Beehive_2.geometry} material={materials.beehive_front} />
      <mesh castShadow receiveShadow geometry={nodes.Beehive_3.geometry} material={materials.beehive_side} />
    </group>
  )
}

useGLTF.preload('/chunk-100--75-lvl-1-transformed.glb')
