/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./maps/chunk225-100-lvl-1.glb --transform --resolution --shadows -o ./maps/chunk225-100-lvl-1.glb-transformed.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/chunk225-100-lvl-1-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Dirt.geometry} material={materials.dirt} />
      <mesh castShadow receiveShadow geometry={nodes.Cobblestone.geometry} material={materials.cobblestone} />
      <mesh castShadow receiveShadow geometry={nodes.Sand.geometry} material={materials.sand} />
      <mesh castShadow receiveShadow geometry={nodes.Gravel.geometry} material={materials.gravel} />
      <mesh castShadow receiveShadow geometry={nodes.Spruce_Leaves.geometry} material={materials.spruce_leaves} />
      <mesh castShadow receiveShadow geometry={nodes.Birch_Leaves.geometry} material={materials.birch_leaves} />
      <mesh castShadow receiveShadow geometry={nodes.Grass.geometry} material={materials.grass} />
      <mesh castShadow receiveShadow geometry={nodes.Dandelion.geometry} material={materials.dandelion} />
      <mesh castShadow receiveShadow geometry={nodes.Poppy.geometry} material={materials.poppy} />
      <mesh castShadow receiveShadow geometry={nodes.Blue_Orchid.geometry} material={materials.blue_orchid} />
      <mesh castShadow receiveShadow geometry={nodes.Azure_Bluet.geometry} material={materials.azure_bluet} />
      <mesh castShadow receiveShadow geometry={nodes.Lily_of_the_Valley.geometry} material={materials.lily_of_the_valley} />
      <mesh castShadow receiveShadow geometry={nodes.Double_Cobblestone_Slab.geometry} material={materials.cobblestone} />
      <mesh castShadow receiveShadow geometry={nodes.Cobblestone_Slab.geometry} material={materials.cobblestone} />
      <mesh castShadow receiveShadow geometry={nodes.Redstone_Wire_power_0.geometry} material={materials.MWO_redstone_dust_dot_off} />
      <mesh castShadow receiveShadow geometry={nodes.Cobblestone_Stairs.geometry} material={materials.cobblestone} />
      <mesh castShadow receiveShadow geometry={nodes.Stone_Button.geometry} material={materials.stone} />
      <mesh castShadow receiveShadow geometry={nodes.Spruce_Stairs.geometry} material={materials.spruce_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Andesite_Wall.geometry} material={materials.andesite} />
      <mesh castShadow receiveShadow geometry={nodes.Acacia_Wood.geometry} material={materials.acacia_log} />
      <mesh castShadow receiveShadow geometry={nodes.Mossy_Cobblestone_Slab.geometry} material={materials.mossy_cobblestone} />
      <mesh castShadow receiveShadow geometry={nodes.Mossy_Cobblestone_Slab_1.geometry} material={materials.mossy_cobblestone} />
      <mesh castShadow receiveShadow geometry={nodes.Brown_Concrete_Powder.geometry} material={materials.brown_concrete_powder} />
      <mesh castShadow receiveShadow geometry={nodes.Sea_Pickle.geometry} material={materials.sea_pickle} />
      <mesh castShadow receiveShadow geometry={nodes.Sea_Pickle__1.geometry} material={materials.sea_pickle} />
      <mesh castShadow receiveShadow geometry={nodes.Sea_Pickle__2.geometry} material={materials.sea_pickle} />
      <mesh castShadow receiveShadow geometry={nodes.Sea_Pickle__3.geometry} material={materials.sea_pickle} />
      <mesh castShadow receiveShadow geometry={nodes.Double_Stone_Slab.geometry} material={materials.stone} />
      <mesh castShadow receiveShadow geometry={nodes.Stone_Slab.geometry} material={materials.stone} />
      <mesh castShadow receiveShadow geometry={nodes.Andesite_Stairs.geometry} material={materials.andesite} />
      <mesh castShadow receiveShadow geometry={nodes.Polished_Andesite_Stairs.geometry} material={materials.polished_andesite} />
      <mesh castShadow receiveShadow geometry={nodes.Grass_Block_1.geometry} material={materials.grass_block_top} />
      <mesh castShadow receiveShadow geometry={nodes.Grass_Block_2.geometry} material={materials.grass_block_side} />
      <mesh castShadow receiveShadow geometry={nodes.Stationary_Water_1.geometry} material={materials.water_still} />
      <mesh castShadow receiveShadow geometry={nodes.Stationary_Water_2.geometry} material={materials.water_flow} />
      <mesh castShadow receiveShadow geometry={nodes.Acacia_Log_1.geometry} material={materials.acacia_log} />
      <mesh castShadow receiveShadow geometry={nodes.Acacia_Log_2.geometry} material={materials.acacia_log_top} />
      <mesh castShadow receiveShadow geometry={nodes.Double_Tallgrass_1.geometry} material={materials.tall_grass_bottom} />
      <mesh castShadow receiveShadow geometry={nodes.Double_Tallgrass_2.geometry} material={materials.tall_grass_top} />
      <mesh castShadow receiveShadow geometry={nodes.Rose_Bush_1.geometry} material={materials.rose_bush_bottom} />
      <mesh castShadow receiveShadow geometry={nodes.Rose_Bush_2.geometry} material={materials.rose_bush_top} />
      <mesh castShadow receiveShadow geometry={nodes.Dirt_Path_1.geometry} material={materials.dirt_path_top} />
      <mesh castShadow receiveShadow geometry={nodes.Dirt_Path_2.geometry} material={materials.dirt_path_side} />
      <mesh castShadow receiveShadow geometry={nodes.Lectern_1.geometry} material={materials.oak_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Lectern_2.geometry} material={materials.lectern_top} />
      <mesh castShadow receiveShadow geometry={nodes.Lectern_3.geometry} material={materials.lectern_sides} />
      <mesh castShadow receiveShadow geometry={nodes.Lectern_4.geometry} material={materials.lectern_base} />
      <mesh castShadow receiveShadow geometry={nodes.Lectern_5.geometry} material={materials.lectern_front} />
    </group>
  )
}

useGLTF.preload('/chunk225-100-lvl-1-transformed.glb')
