/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./maps/chunk-175-175-lvl-1.glb --transform --resolution --shadows -o ./maps/chunk-175-175-lvl-1-transformed.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/chunk-175-175-lvl-1-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Stone.geometry} material={materials.stone} />
      <mesh castShadow receiveShadow geometry={nodes.Granite.geometry} material={materials.granite} />
      <mesh castShadow receiveShadow geometry={nodes.Andesite.geometry} material={materials.andesite} />
      <mesh castShadow receiveShadow geometry={nodes.Dirt.geometry} material={materials.dirt} />
      <mesh castShadow receiveShadow geometry={nodes.Oak_Planks.geometry} material={materials.oak_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Birch_Wood_Planks.geometry} material={materials.birch_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Sand.geometry} material={materials.sand} />
      <mesh castShadow receiveShadow geometry={nodes.Torch.geometry} material={materials.torch} />
      <mesh castShadow receiveShadow geometry={nodes.Oak_Stairs.geometry} material={materials.oak_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Ladder.geometry} material={materials.ladder} />
      <mesh castShadow receiveShadow geometry={nodes.Fence.geometry} material={materials.oak_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Oak_Slab.geometry} material={materials.oak_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Acacia_Leaves.geometry} material={materials.acacia_leaves} />
      <mesh castShadow receiveShadow geometry={nodes.Spruce_Button.geometry} material={materials.spruce_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Lantern.geometry} material={materials.lantern} />
      <mesh castShadow receiveShadow geometry={nodes.Grass_Block_1.geometry} material={materials.grass_block_top} />
      <mesh castShadow receiveShadow geometry={nodes.Grass_Block_2.geometry} material={materials.grass_block_side} />
      <mesh castShadow receiveShadow geometry={nodes.Sandstone_1.geometry} material={materials.sandstone_top} />
      <mesh castShadow receiveShadow geometry={nodes.Sandstone_2.geometry} material={materials.sandstone} />
      <mesh castShadow receiveShadow geometry={nodes.Sandstone_3.geometry} material={materials.sandstone_bottom} />
      <mesh castShadow receiveShadow geometry={nodes.Cut_Sandstone_1.geometry} material={materials.sandstone_top} />
      <mesh castShadow receiveShadow geometry={nodes.Cut_Sandstone_2.geometry} material={materials.cut_sandstone} />
      <mesh castShadow receiveShadow geometry={nodes.Bed_1.geometry} material={materials.oak_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Bed_2.geometry} material={materials.MW_bed_feet_top} />
      <mesh castShadow receiveShadow geometry={nodes.Bed_3.geometry} material={materials.MW_bed_head_top} />
      <mesh castShadow receiveShadow geometry={nodes.Bed_4.geometry} material={materials.MW_bed_feet_end} />
      <mesh castShadow receiveShadow geometry={nodes.Bed_5.geometry} material={materials.MW_bed_feet_side} />
      <mesh castShadow receiveShadow geometry={nodes.Bed_6.geometry} material={materials.MW_bed_head_side} />
      <mesh castShadow receiveShadow geometry={nodes.Bed_7.geometry} material={materials.MW_bed_head_end} />
      <mesh castShadow receiveShadow geometry={nodes.Sandstone_Slab_1.geometry} material={materials.sandstone_top} />
      <mesh castShadow receiveShadow geometry={nodes.Sandstone_Slab_2.geometry} material={materials.sandstone} />
      <mesh castShadow receiveShadow geometry={nodes.Sandstone_Slab_3.geometry} material={materials.sandstone_bottom} />
      <mesh castShadow receiveShadow geometry={nodes.Furnace_1.geometry} material={materials.furnace_front} />
      <mesh castShadow receiveShadow geometry={nodes.Furnace_2.geometry} material={materials.furnace_side} />
      <mesh castShadow receiveShadow geometry={nodes.Furnace_3.geometry} material={materials.furnace_top} />
      <mesh castShadow receiveShadow geometry={nodes.Sandstone_Stairs_1.geometry} material={materials.sandstone_top} />
      <mesh castShadow receiveShadow geometry={nodes.Sandstone_Stairs_2.geometry} material={materials.sandstone} />
      <mesh castShadow receiveShadow geometry={nodes.Sandstone_Stairs_3.geometry} material={materials.sandstone_bottom} />
      <mesh castShadow receiveShadow geometry={nodes.Cut_Red_Sandstone_1.geometry} material={materials.cut_red_sandstone} />
      <mesh castShadow receiveShadow geometry={nodes.Cut_Red_Sandstone_2.geometry} material={materials.red_sandstone_top} />
      <mesh castShadow receiveShadow geometry={nodes.Cut_Sandstone_Slab_1.geometry} material={materials.sandstone_top} />
      <mesh castShadow receiveShadow geometry={nodes.Cut_Sandstone_Slab_2.geometry} material={materials.cut_sandstone} />
      <mesh castShadow receiveShadow geometry={nodes.Spruce_Door_1.geometry} material={materials.spruce_door_bottom} />
      <mesh castShadow receiveShadow geometry={nodes.Spruce_Door_2.geometry} material={materials.spruce_door_top} />
      <mesh castShadow receiveShadow geometry={nodes.Barrel_1.geometry} material={materials.barrel_top} />
      <mesh castShadow receiveShadow geometry={nodes.Barrel_2.geometry} material={materials.barrel_side} />
      <mesh castShadow receiveShadow geometry={nodes.Scaffolding_1.geometry} material={materials.scaffolding_top} />
      <mesh castShadow receiveShadow geometry={nodes.Scaffolding_2.geometry} material={materials.scaffolding_side} />
      <mesh castShadow receiveShadow geometry={nodes.Scaffolding_3.geometry} material={materials.scaffolding_bottom} />
    </group>
  )
}

useGLTF.preload('/chunk-175-175-lvl-1-transformed.glb')
