/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./maps/chunk0-475-lvl-1.glb --transform --resolution --shadows -o ./maps/chunk0-475-lvl-1.glb-transformed.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/chunk0-475-lvl-1-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Stone.geometry} material={materials.stone} />
      <mesh castShadow receiveShadow geometry={nodes.Granite.geometry} material={materials.granite} />
      <mesh castShadow receiveShadow geometry={nodes.Diorite.geometry} material={materials.diorite} />
      <mesh castShadow receiveShadow geometry={nodes.Andesite.geometry} material={materials.andesite} />
      <mesh castShadow receiveShadow geometry={nodes.Polished_Andesite.geometry} material={materials.polished_andesite} />
      <mesh castShadow receiveShadow geometry={nodes.Dirt.geometry} material={materials.dirt} />
      <mesh castShadow receiveShadow geometry={nodes.Sand.geometry} material={materials.sand} />
      <mesh castShadow receiveShadow geometry={nodes.Gravel.geometry} material={materials.gravel} />
      <mesh castShadow receiveShadow geometry={nodes.Coal_Ore.geometry} material={materials.coal_ore} />
      <mesh castShadow receiveShadow geometry={nodes.Block_of_Gold.geometry} material={materials.gold_block} />
      <mesh castShadow receiveShadow geometry={nodes.Block_of_Iron.geometry} material={materials.iron_block} />
      <mesh castShadow receiveShadow geometry={nodes.Torch.geometry} material={materials.torch} />
      <mesh castShadow receiveShadow geometry={nodes.Ladder.geometry} material={materials.ladder} />
      <mesh castShadow receiveShadow geometry={nodes.Oak_Wall_Sign.geometry} material={materials.oak_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Fence.geometry} material={materials.oak_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Oak_Trapdoor.geometry} material={materials.oak_trapdoor} />
      <mesh castShadow receiveShadow geometry={nodes.Iron_Bars.geometry} material={materials.iron_bars} />
      <mesh castShadow receiveShadow geometry={nodes.Block_of_Quartz.geometry} material={materials.quartz_pillar} />
      <mesh castShadow receiveShadow geometry={nodes.Quartz_Stairs.geometry} material={materials.quartz_block_side} />
      <mesh castShadow receiveShadow geometry={nodes.Yellow_Terracotta.geometry} material={materials.yellow_terracotta} />
      <mesh castShadow receiveShadow geometry={nodes.Blue_Terracotta.geometry} material={materials.blue_terracotta} />
      <mesh castShadow receiveShadow geometry={nodes.Red_Terracotta.geometry} material={materials.red_terracotta} />
      <mesh castShadow receiveShadow geometry={nodes.Spruce_Trapdoor.geometry} material={materials.spruce_trapdoor} />
      <mesh castShadow receiveShadow geometry={nodes.Grass_Block_1.geometry} material={materials.grass_block_top} />
      <mesh castShadow receiveShadow geometry={nodes.Grass_Block_2.geometry} material={materials.grass_block_side} />
      <mesh castShadow receiveShadow geometry={nodes.Stationary_Water_1.geometry} material={materials.water_still} />
      <mesh castShadow receiveShadow geometry={nodes.Stationary_Water_2.geometry} material={materials.water_flow} />
      <mesh castShadow receiveShadow geometry={nodes.Sandstone_1.geometry} material={materials.sandstone_top} />
      <mesh castShadow receiveShadow geometry={nodes.Sandstone_2.geometry} material={materials.sandstone} />
      <mesh castShadow receiveShadow geometry={nodes.Sandstone_3.geometry} material={materials.sandstone_bottom} />
      <mesh castShadow receiveShadow geometry={nodes.Chiseled_Sandstone_1.geometry} material={materials.sandstone_top} />
      <mesh castShadow receiveShadow geometry={nodes.Chiseled_Sandstone_2.geometry} material={materials.chiseled_sandstone} />
      <mesh castShadow receiveShadow geometry={nodes.Cut_Sandstone_1.geometry} material={materials.sandstone_top} />
      <mesh castShadow receiveShadow geometry={nodes.Cut_Sandstone_2.geometry} material={materials.cut_sandstone} />
      <mesh castShadow receiveShadow geometry={nodes.Bed_1.geometry} material={materials.oak_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Bed_2.geometry} material={materials.MW_bed_feet_top} />
      <mesh castShadow receiveShadow geometry={nodes.Bed_3.geometry} material={materials.MW_bed_feet_end} />
      <mesh castShadow receiveShadow geometry={nodes.Bed_4.geometry} material={materials.MW_bed_feet_side} />
      <mesh castShadow receiveShadow geometry={nodes.Sandstone_Slab_1.geometry} material={materials.sandstone_top} />
      <mesh castShadow receiveShadow geometry={nodes.Sandstone_Slab_2.geometry} material={materials.sandstone} />
      <mesh castShadow receiveShadow geometry={nodes.Sandstone_Slab_3.geometry} material={materials.sandstone_bottom} />
      <mesh castShadow receiveShadow geometry={nodes.Quartz_Slab_1.geometry} material={materials.quartz_block_bottom} />
      <mesh castShadow receiveShadow geometry={nodes.Quartz_Slab_2.geometry} material={materials.quartz_block_side} />
      <mesh castShadow receiveShadow geometry={nodes.Quartz_Slab_3.geometry} material={materials.quartz_block_side} />
      <mesh castShadow receiveShadow geometry={nodes.Chest_1.geometry} material={materials.MWO_chest_top} />
      <mesh castShadow receiveShadow geometry={nodes.Chest_2.geometry} material={materials.MWO_chest_side} />
      <mesh castShadow receiveShadow geometry={nodes.Chest_3.geometry} material={materials.MWO_chest_front} />
      <mesh castShadow receiveShadow geometry={nodes.Chest_4.geometry} material={materials.MWO_chest_latch} />
      <mesh castShadow receiveShadow geometry={nodes.Crafting_Table_1.geometry} material={materials.crafting_table_top} />
      <mesh castShadow receiveShadow geometry={nodes.Crafting_Table_2.geometry} material={materials.crafting_table_side} />
      <mesh castShadow receiveShadow geometry={nodes.Crafting_Table_3.geometry} material={materials.crafting_table_front} />
      <mesh castShadow receiveShadow geometry={nodes.Oak_Door_1.geometry} material={materials.oak_door_top} />
      <mesh castShadow receiveShadow geometry={nodes.Oak_Door_2.geometry} material={materials.oak_door_bottom} />
      <mesh castShadow receiveShadow geometry={nodes.Sandstone_Stairs_1.geometry} material={materials.sandstone_top} />
      <mesh castShadow receiveShadow geometry={nodes.Sandstone_Stairs_2.geometry} material={materials.sandstone} />
      <mesh castShadow receiveShadow geometry={nodes.Sandstone_Stairs_3.geometry} material={materials.sandstone_bottom} />
      <mesh castShadow receiveShadow geometry={nodes.Flower_Pot_1.geometry} material={materials.dirt} />
      <mesh castShadow receiveShadow geometry={nodes.Flower_Pot_2.geometry} material={materials.flower_pot} />
      <mesh castShadow receiveShadow geometry={nodes.Light_Stained_Glass_Pane_1.geometry} material={materials.light_blue_stained_glass} />
      <mesh castShadow receiveShadow geometry={nodes.Light_Stained_Glass_Pane_2.geometry} material={materials.light_blue_stained_glass_pane_top} />
      <mesh castShadow receiveShadow geometry={nodes.Yellow_Stained_Glass_Pane_1.geometry} material={materials.yellow_stained_glass} />
      <mesh castShadow receiveShadow geometry={nodes.Yellow_Stained_Glass_Pane_2.geometry} material={materials.yellow_stained_glass_pane_top} />
      <mesh castShadow receiveShadow geometry={nodes.Red_Stained_Glass_Pane_1.geometry} material={materials.red_stained_glass} />
      <mesh castShadow receiveShadow geometry={nodes.Red_Stained_Glass_Pane_2.geometry} material={materials.red_stained_glass_pane_top} />
      <mesh castShadow receiveShadow geometry={nodes.Cut_Sandstone_Slab_2.geometry} material={materials.sandstone_top} />
      <mesh castShadow receiveShadow geometry={nodes.Cut_Sandstone_Slab_3.geometry} material={materials.cut_sandstone} />
      <mesh castShadow receiveShadow geometry={nodes.Cut_Sandstone_Slab_1_1.geometry} material={materials.cut_sandstone} />
      <mesh castShadow receiveShadow geometry={nodes.Cut_Sandstone_Slab_1_2.geometry} material={materials.sandstone_top} />
    </group>
  )
}

useGLTF.preload('/chunk0-475-lvl-1-transformed.glb')
