/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./maps/chunk-150-550-lvl-1.glb --transform --resolution --shadows -o ./maps/chunk-150-550-lvl-1-transformed.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/chunk-150-550-lvl-1-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Stone.geometry} material={materials.stone} />
      <mesh castShadow receiveShadow geometry={nodes.Granite.geometry} material={materials.granite} />
      <mesh castShadow receiveShadow geometry={nodes.Diorite.geometry} material={materials.diorite} />
      <mesh castShadow receiveShadow geometry={nodes.Andesite.geometry} material={materials.andesite} />
      <mesh castShadow receiveShadow geometry={nodes.Dirt.geometry} material={materials.dirt} />
      <mesh castShadow receiveShadow geometry={nodes.Cobblestone.geometry} material={materials.cobblestone} />
      <mesh castShadow receiveShadow geometry={nodes.Stationary_Water.geometry} material={materials.water_still} />
      <mesh castShadow receiveShadow geometry={nodes.Sand.geometry} material={materials.sand} />
      <mesh castShadow receiveShadow geometry={nodes.Gravel.geometry} material={materials.gravel} />
      <mesh castShadow receiveShadow geometry={nodes.Coal_Ore.geometry} material={materials.coal_ore} />
      <mesh castShadow receiveShadow geometry={nodes.Oak_Leaves.geometry} material={materials.oak_leaves} />
      <mesh castShadow receiveShadow geometry={nodes.Grass.geometry} material={materials.grass} />
      <mesh castShadow receiveShadow geometry={nodes.Torch.geometry} material={materials.torch} />
      <mesh castShadow receiveShadow geometry={nodes.Oak_Stairs.geometry} material={materials.oak_planks} />
      <mesh castShadow receiveShadow geometry={nodes['Redstone_Torch_(active)'].geometry} material={materials.redstone_torch} />
      <mesh castShadow receiveShadow geometry={nodes.Snow.geometry} material={materials.snow} />
      <mesh castShadow receiveShadow geometry={nodes.Fence.geometry} material={materials.oak_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Soul_Sand.geometry} material={materials.soul_sand} />
      <mesh castShadow receiveShadow geometry={nodes.Fence_Gate.geometry} material={materials.oak_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Andesite_Wall.geometry} material={materials.andesite} />
      <mesh castShadow receiveShadow geometry={nodes.Brown_Carpet.geometry} material={materials.brown_wool} />
      <mesh castShadow receiveShadow geometry={nodes.Basalt.geometry} material={materials.basalt_side} />
      <mesh castShadow receiveShadow geometry={nodes.Stripped_Birch_Wood.geometry} material={materials.stripped_birch_log} />
      <mesh castShadow receiveShadow geometry={nodes.Tall_Seagrass.geometry} material={materials.tall_seagrass_bottom} />
      <mesh castShadow receiveShadow geometry={nodes.Seagrass.geometry} material={materials.tall_seagrass_top} />
      <mesh castShadow receiveShadow geometry={nodes.Double_Stone_Slab.geometry} material={materials.stone} />
      <mesh castShadow receiveShadow geometry={nodes.Stone_Slab.geometry} material={materials.stone} />
      <mesh castShadow receiveShadow geometry={nodes.Lantern.geometry} material={materials.lantern} />
      <mesh castShadow receiveShadow geometry={nodes.Stone_Stairs.geometry} material={materials.stone} />
      <mesh castShadow receiveShadow geometry={nodes.Andesite_Stairs.geometry} material={materials.andesite} />
      <mesh castShadow receiveShadow geometry={nodes.Grass_Block_1.geometry} material={materials.grass_block_top} />
      <mesh castShadow receiveShadow geometry={nodes.Grass_Block_2.geometry} material={materials.dirt} />
      <mesh castShadow receiveShadow geometry={nodes.Grass_Block_3.geometry} material={materials.grass_block_side} />
      <mesh castShadow receiveShadow geometry={nodes.Grass_Block_4.geometry} material={materials.snow} />
      <mesh castShadow receiveShadow geometry={nodes.Grass_Block_5.geometry} material={materials.grass_block_snow} />
      <mesh castShadow receiveShadow geometry={nodes.Oak_Log_1.geometry} material={materials.oak_log} />
      <mesh castShadow receiveShadow geometry={nodes.Oak_Log_2.geometry} material={materials.oak_log_top} />
      <mesh castShadow receiveShadow geometry={nodes.Sandstone_1.geometry} material={materials.sandstone_top} />
      <mesh castShadow receiveShadow geometry={nodes.Sandstone_2.geometry} material={materials.sandstone} />
      <mesh castShadow receiveShadow geometry={nodes.Sandstone_3.geometry} material={materials.sandstone_bottom} />
      <mesh castShadow receiveShadow geometry={nodes.Cut_Sandstone_1.geometry} material={materials.sandstone_top} />
      <mesh castShadow receiveShadow geometry={nodes.Cut_Sandstone_2.geometry} material={materials.cut_sandstone} />
      <mesh castShadow receiveShadow geometry={nodes.Sandstone_Slab_1.geometry} material={materials.sandstone_top} />
      <mesh castShadow receiveShadow geometry={nodes.Sandstone_Slab_2.geometry} material={materials.sandstone} />
      <mesh castShadow receiveShadow geometry={nodes.Sandstone_Slab_3.geometry} material={materials.sandstone_bottom} />
      <mesh castShadow receiveShadow geometry={nodes.Cauldron_1.geometry} material={materials.cauldron_top} />
      <mesh castShadow receiveShadow geometry={nodes.Cauldron_2.geometry} material={materials.cauldron_inner} />
      <mesh castShadow receiveShadow geometry={nodes.Cauldron_3.geometry} material={materials.cauldron_side} />
      <mesh castShadow receiveShadow geometry={nodes.Sandstone_Stairs_1.geometry} material={materials.sandstone_top} />
      <mesh castShadow receiveShadow geometry={nodes.Sandstone_Stairs_2.geometry} material={materials.sandstone} />
      <mesh castShadow receiveShadow geometry={nodes.Sandstone_Stairs_3.geometry} material={materials.sandstone_bottom} />
      <mesh castShadow receiveShadow geometry={nodes.Hay_Bale_1.geometry} material={materials.hay_block_side} />
      <mesh castShadow receiveShadow geometry={nodes.Hay_Bale_2.geometry} material={materials.hay_block_top} />
      <mesh castShadow receiveShadow geometry={nodes.Sunflower_1.geometry} material={materials.sunflower_back} />
      <mesh castShadow receiveShadow geometry={nodes.Sunflower_2.geometry} material={materials.sunflower_front} />
      <mesh castShadow receiveShadow geometry={nodes.Sunflower_3.geometry} material={materials.sunflower_bottom} />
      <mesh castShadow receiveShadow geometry={nodes.Sunflower_4.geometry} material={materials.sunflower_top} />
      <mesh castShadow receiveShadow geometry={nodes.Barrel_1.geometry} material={materials.barrel_side} />
      <mesh castShadow receiveShadow geometry={nodes.Barrel_2.geometry} material={materials.barrel_bottom} />
      <mesh castShadow receiveShadow geometry={nodes.Lectern_1.geometry} material={materials.oak_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Lectern_2.geometry} material={materials.lectern_top} />
      <mesh castShadow receiveShadow geometry={nodes.Lectern_3.geometry} material={materials.lectern_sides} />
      <mesh castShadow receiveShadow geometry={nodes.Lectern_4.geometry} material={materials.lectern_base} />
      <mesh castShadow receiveShadow geometry={nodes.Lectern_5.geometry} material={materials.lectern_front} />
    </group>
  )
}

useGLTF.preload('/chunk-150-550-lvl-1-transformed.glb')
