/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./maps/chunk0-75-lvl-1.glb --transform --resolution --shadows -o ./maps/chunk0-75-lvl-1.glb-transformed.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/chunk0-75-lvl-1-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Yellow_Wool.geometry} material={materials.yellow_wool} />
      <mesh castShadow receiveShadow geometry={nodes.Block_of_Gold.geometry} material={materials.gold_block} />
      <mesh castShadow receiveShadow geometry={nodes.Torch.geometry} material={materials.torch} />
      <mesh castShadow receiveShadow geometry={nodes.Fire.geometry} material={materials.fire_0} />
      <mesh castShadow receiveShadow geometry={nodes.Netherrack.geometry} material={materials.netherrack} />
      <mesh castShadow receiveShadow geometry={nodes.Glowstone.geometry} material={materials.glowstone} />
      <mesh castShadow receiveShadow geometry={nodes.Quartz_Stairs.geometry} material={materials.quartz_block_side} />
      <mesh castShadow receiveShadow geometry={nodes.Acacia_Fence.geometry} material={materials.acacia_planks} />
      <mesh castShadow receiveShadow geometry={nodes.End_Rod.geometry} material={materials.end_rod} />
      <mesh castShadow receiveShadow geometry={nodes.Quartz.geometry} material={materials.quartz_block_bottom} />
      <mesh castShadow receiveShadow geometry={nodes.Smooth_Quartz_Stairs.geometry} material={materials.quartz_block_side} />
      <mesh castShadow receiveShadow geometry={nodes.Stationary_Water_1.geometry} material={materials.water_still} />
      <mesh castShadow receiveShadow geometry={nodes.Stationary_Water_2.geometry} material={materials.water_flow} />
      <mesh castShadow receiveShadow geometry={nodes.Sandstone_1.geometry} material={materials.sandstone_top} />
      <mesh castShadow receiveShadow geometry={nodes.Sandstone_2.geometry} material={materials.sandstone} />
      <mesh castShadow receiveShadow geometry={nodes.Double_Quartz_Slab_1.geometry} material={materials.quartz_block_bottom} />
      <mesh castShadow receiveShadow geometry={nodes.Double_Quartz_Slab_2.geometry} material={materials.quartz_block_side} />
      <mesh castShadow receiveShadow geometry={nodes.Double_Quartz_Slab_3.geometry} material={materials.quartz_block_side} />
      <mesh castShadow receiveShadow geometry={nodes.Quartz_Slab_1.geometry} material={materials.quartz_block_side} />
      <mesh castShadow receiveShadow geometry={nodes.Quartz_Slab_2.geometry} material={materials.quartz_block_bottom} />
      <mesh castShadow receiveShadow geometry={nodes.Quartz_Slab_3.geometry} material={materials.quartz_block_side} />
      <mesh castShadow receiveShadow geometry={nodes.Birch_Sign_1.geometry} material={materials.birch_log} />
      <mesh castShadow receiveShadow geometry={nodes.Birch_Sign_2.geometry} material={materials.spruce_log_top} />
      <mesh castShadow receiveShadow geometry={nodes.Birch_Sign_3.geometry} material={materials.birch_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Trapped_Chest_1.geometry} material={materials.MWO_chest_side} />
      <mesh castShadow receiveShadow geometry={nodes.Trapped_Chest_2.geometry} material={materials.MWO_double_chest_front_left} />
      <mesh castShadow receiveShadow geometry={nodes.Trapped_Chest_3.geometry} material={materials.MWO_double_chest_front_right} />
      <mesh castShadow receiveShadow geometry={nodes.Trapped_Chest_4.geometry} material={materials.MWO_double_chest_back_left} />
      <mesh castShadow receiveShadow geometry={nodes.Trapped_Chest_5.geometry} material={materials.MWO_double_chest_back_right} />
      <mesh castShadow receiveShadow geometry={nodes.Trapped_Chest_6.geometry} material={materials.MWO_double_chest_top_left} />
      <mesh castShadow receiveShadow geometry={nodes.Trapped_Chest_7.geometry} material={materials.MWO_double_chest_top_right} />
      <mesh castShadow receiveShadow geometry={nodes.Trapped_Chest_8.geometry} material={materials.MWO_chest_latch} />
      <mesh castShadow receiveShadow geometry={nodes.Block_of_Quartz_1.geometry} material={materials.quartz_pillar_top} />
      <mesh castShadow receiveShadow geometry={nodes.Block_of_Quartz_2.geometry} material={materials.quartz_pillar} />
      <mesh castShadow receiveShadow geometry={nodes.Block_of_Quartz_3.geometry} material={materials.quartz_block_side} />
      <mesh castShadow receiveShadow geometry={nodes.Block_of_Quartz_4.geometry} material={materials.quartz_block_side} />
      <mesh castShadow receiveShadow geometry={nodes.Chiseled_Quartz_Block_1.geometry} material={materials.chiseled_quartz_block_top} />
      <mesh castShadow receiveShadow geometry={nodes.Chiseled_Quartz_Block_2.geometry} material={materials.chiseled_quartz_block} />
    </group>
  )
}

useGLTF.preload('/chunk0-75-lvl-1-transformed.glb')
