/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./maps/chunk-225-450-lvl-1.glb --transform --resolution --shadows -o ./maps/chunk-225-450-lvl-1-transformed.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/chunk-225-450-lvl-1-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Granite.geometry} material={materials.granite} />
      <mesh castShadow receiveShadow geometry={nodes.Diorite.geometry} material={materials.diorite} />
      <mesh castShadow receiveShadow geometry={nodes.Polished_Andesite.geometry} material={materials.polished_andesite} />
      <mesh castShadow receiveShadow geometry={nodes.Dirt.geometry} material={materials.dirt} />
      <mesh castShadow receiveShadow geometry={nodes.Oak_Planks.geometry} material={materials.oak_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Stationary_Water.geometry} material={materials.water_still} />
      <mesh castShadow receiveShadow geometry={nodes.Grass.geometry} material={materials.grass} />
      <mesh castShadow receiveShadow geometry={nodes.Dandelion.geometry} material={materials.dandelion} />
      <mesh castShadow receiveShadow geometry={nodes.Block_of_Gold.geometry} material={materials.gold_block} />
      <mesh castShadow receiveShadow geometry={nodes.Torch.geometry} material={materials.torch} />
      <mesh castShadow receiveShadow geometry={nodes.Ladder.geometry} material={materials.ladder} />
      <mesh castShadow receiveShadow geometry={nodes.Oak_Wall_Sign.geometry} material={materials.oak_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Spruce_Wall_Sign.geometry} material={materials.spruce_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Fence.geometry} material={materials.oak_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Oak_Trapdoor.geometry} material={materials.oak_trapdoor} />
      <mesh castShadow receiveShadow geometry={nodes.Stone_Bricks.geometry} material={materials.stone_bricks} />
      <mesh castShadow receiveShadow geometry={nodes.Oak_Slab.geometry} material={materials.oak_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Oak_Button.geometry} material={materials.oak_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Orange_Terracotta.geometry} material={materials.orange_terracotta} />
      <mesh castShadow receiveShadow geometry={nodes.Red_Terracotta.geometry} material={materials.red_terracotta} />
      <mesh castShadow receiveShadow geometry={nodes.Spruce_Trapdoor.geometry} material={materials.spruce_trapdoor} />
      <mesh castShadow receiveShadow geometry={nodes.Grass_Block_1.geometry} material={materials.grass_block_top} />
      <mesh castShadow receiveShadow geometry={nodes.Grass_Block_2.geometry} material={materials.dirt} />
      <mesh castShadow receiveShadow geometry={nodes.Grass_Block_3.geometry} material={materials.grass_block_side} />
      <mesh castShadow receiveShadow geometry={nodes.Sandstone_1.geometry} material={materials.sandstone_top} />
      <mesh castShadow receiveShadow geometry={nodes.Sandstone_2.geometry} material={materials.sandstone} />
      <mesh castShadow receiveShadow geometry={nodes.Sandstone_3.geometry} material={materials.sandstone_bottom} />
      <mesh castShadow receiveShadow geometry={nodes.Cut_Sandstone_1.geometry} material={materials.sandstone_top} />
      <mesh castShadow receiveShadow geometry={nodes.Cut_Sandstone_2.geometry} material={materials.cut_sandstone} />
      <mesh castShadow receiveShadow geometry={nodes.Double_Sandstone_Slab_1.geometry} material={materials.sandstone_top} />
      <mesh castShadow receiveShadow geometry={nodes.Double_Sandstone_Slab_2.geometry} material={materials.sandstone} />
      <mesh castShadow receiveShadow geometry={nodes.Double_Sandstone_Slab_3.geometry} material={materials.sandstone_bottom} />
      <mesh castShadow receiveShadow geometry={nodes.Sandstone_Slab_1.geometry} material={materials.sandstone_bottom} />
      <mesh castShadow receiveShadow geometry={nodes.Sandstone_Slab_2.geometry} material={materials.sandstone_top} />
      <mesh castShadow receiveShadow geometry={nodes.Sandstone_Slab_3.geometry} material={materials.sandstone} />
      <mesh castShadow receiveShadow geometry={nodes.Oak_Door_1.geometry} material={materials.oak_door_top} />
      <mesh castShadow receiveShadow geometry={nodes.Oak_Door_2.geometry} material={materials.oak_door_bottom} />
      <mesh castShadow receiveShadow geometry={nodes.Sandstone_Stairs_1.geometry} material={materials.sandstone_top} />
      <mesh castShadow receiveShadow geometry={nodes.Sandstone_Stairs_2.geometry} material={materials.sandstone} />
      <mesh castShadow receiveShadow geometry={nodes.Sandstone_Stairs_3.geometry} material={materials.sandstone_bottom} />
      <mesh castShadow receiveShadow geometry={nodes.Light_Stained_Glass_Pane_1.geometry} material={materials.light_blue_stained_glass} />
      <mesh castShadow receiveShadow geometry={nodes.Light_Stained_Glass_Pane_2.geometry} material={materials.light_blue_stained_glass_pane_top} />
      <mesh castShadow receiveShadow geometry={nodes.Yellow_Stained_Glass_Pane_1.geometry} material={materials.yellow_stained_glass} />
      <mesh castShadow receiveShadow geometry={nodes.Yellow_Stained_Glass_Pane_2.geometry} material={materials.yellow_stained_glass_pane_top} />
      <mesh castShadow receiveShadow geometry={nodes.Red_Stained_Glass_Pane_1.geometry} material={materials.red_stained_glass} />
      <mesh castShadow receiveShadow geometry={nodes.Red_Stained_Glass_Pane_2.geometry} material={materials.red_stained_glass_pane_top} />
      <mesh castShadow receiveShadow geometry={nodes.Cut_Sandstone_Slab_1.geometry} material={materials.sandstone_top} />
      <mesh castShadow receiveShadow geometry={nodes.Cut_Sandstone_Slab_2.geometry} material={materials.cut_sandstone} />
    </group>
  )
}

useGLTF.preload('/chunk-225-450-lvl-1-transformed.glb')
