/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./maps/chunk-125--50-lvl-1.glb --transform --resolution --shadows -o ./maps/chunk-125--50-lvl-1-transformed.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/chunk-125--50-lvl-1-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Stone.geometry} material={materials.stone} />
      <mesh castShadow receiveShadow geometry={nodes.Gravel.geometry} material={materials.gravel} />
      <mesh castShadow receiveShadow geometry={nodes.Cobblestone_Stairs.geometry} material={materials.cobblestone} />
      <mesh castShadow receiveShadow geometry={nodes.Double_Stone_Slab.geometry} material={materials.stone} />
      <mesh castShadow receiveShadow geometry={nodes.Stone_Slab.geometry} material={materials.stone} />
    </group>
  )
}

useGLTF.preload('/chunk-125--50-lvl-1-transformed.glb')
