/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./maps/chunk-175-550-lvl-1.glb --transform --resolution --shadows -o ./maps/chunk-175-550-lvl-1-transformed.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/chunk-175-550-lvl-1-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Stone.geometry} material={materials.stone} />
      <mesh castShadow receiveShadow geometry={nodes.Dirt.geometry} material={materials.dirt} />
      <mesh castShadow receiveShadow geometry={nodes.Stationary_Water.geometry} material={materials.water_still} />
      <mesh castShadow receiveShadow geometry={nodes.Sand.geometry} material={materials.sand} />
      <mesh castShadow receiveShadow geometry={nodes.Gravel.geometry} material={materials.gravel} />
      <mesh castShadow receiveShadow geometry={nodes.Coal_Ore.geometry} material={materials.coal_ore} />
      <mesh castShadow receiveShadow geometry={nodes.Oak_Leaves.geometry} material={materials.oak_leaves} />
      <mesh castShadow receiveShadow geometry={nodes.Sandstone.geometry} material={materials.sandstone_top} />
      <mesh castShadow receiveShadow geometry={nodes.Grass.geometry} material={materials.grass} />
      <mesh castShadow receiveShadow geometry={nodes.Oxeye_Daisy.geometry} material={materials.oxeye_daisy} />
      <mesh castShadow receiveShadow geometry={nodes.Clay.geometry} material={materials.clay} />
      <mesh castShadow receiveShadow geometry={nodes.Soul_Sand.geometry} material={materials.soul_sand} />
      <mesh castShadow receiveShadow geometry={nodes.Stripped_Birch_Wood.geometry} material={materials.stripped_birch_log} />
      <mesh castShadow receiveShadow geometry={nodes.Seagrass.geometry} material={materials.tall_seagrass_top} />
      <mesh castShadow receiveShadow geometry={nodes.Grass_Block_1.geometry} material={materials.grass_block_top} />
      <mesh castShadow receiveShadow geometry={nodes.Grass_Block_2.geometry} material={materials.grass_block_side} />
      <mesh castShadow receiveShadow geometry={nodes.Oak_Log_1.geometry} material={materials.oak_log} />
      <mesh castShadow receiveShadow geometry={nodes.Oak_Log_2.geometry} material={materials.oak_log_top} />
      <mesh castShadow receiveShadow geometry={nodes.Cut_Sandstone_1.geometry} material={materials.sandstone_top} />
      <mesh castShadow receiveShadow geometry={nodes.Cut_Sandstone_2.geometry} material={materials.cut_sandstone} />
      <mesh castShadow receiveShadow geometry={nodes.Sunflower_1.geometry} material={materials.sunflower_back} />
      <mesh castShadow receiveShadow geometry={nodes.Sunflower_2.geometry} material={materials.sunflower_front} />
      <mesh castShadow receiveShadow geometry={nodes.Sunflower_3.geometry} material={materials.sunflower_bottom} />
      <mesh castShadow receiveShadow geometry={nodes.Sunflower_4.geometry} material={materials.sunflower_top} />
      <mesh castShadow receiveShadow geometry={nodes.Double_Tallgrass_1.geometry} material={materials.tall_grass_bottom} />
      <mesh castShadow receiveShadow geometry={nodes.Double_Tallgrass_2.geometry} material={materials.tall_grass_top} />
      <mesh castShadow receiveShadow geometry={nodes.Tall_Seagrass_1.geometry} material={materials.tall_seagrass_bottom} />
      <mesh castShadow receiveShadow geometry={nodes.Tall_Seagrass_2.geometry} material={materials.tall_seagrass_top} />
      <mesh castShadow receiveShadow geometry={nodes.Bee_Nest_1.geometry} material={materials.bee_nest_bottom} />
      <mesh castShadow receiveShadow geometry={nodes.Bee_Nest_2.geometry} material={materials.bee_nest_front} />
      <mesh castShadow receiveShadow geometry={nodes.Bee_Nest_3.geometry} material={materials.bee_nest_front_honey} />
      <mesh castShadow receiveShadow geometry={nodes.Bee_Nest_4.geometry} material={materials.bee_nest_side} />
      <mesh castShadow receiveShadow geometry={nodes.Bee_Nest_5.geometry} material={materials.bee_nest_top} />
    </group>
  )
}

useGLTF.preload('/chunk-175-550-lvl-1-transformed.glb')
