/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./maps/chunk-100--75-lvl-1.glb --transform --resolution --shadows -o ./maps/chunk-100--75-lvl-1.glb-transformed.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/chunk-100--75-lvl-1-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Stone.geometry} material={materials.stone} />
      <mesh castShadow receiveShadow geometry={nodes.Dirt.geometry} material={materials.dirt} />
      <mesh castShadow receiveShadow geometry={nodes.Gravel.geometry} material={materials.gravel} />
      <mesh castShadow receiveShadow geometry={nodes.Double_Cobblestone_Slab.geometry} material={materials.cobblestone} />
      <mesh castShadow receiveShadow geometry={nodes.Double_Stone_Brick_Slab.geometry} material={materials.stone_bricks} />
      <mesh castShadow receiveShadow geometry={nodes.Cobblestone_Slab.geometry} material={materials.cobblestone} />
      <mesh castShadow receiveShadow geometry={nodes.Stone_Brick_Slab.geometry} material={materials.stone_bricks} />
      <mesh castShadow receiveShadow geometry={nodes.Redstone_Wire_power_0.geometry} material={materials.MWO_redstone_dust_dot_off} />
      <mesh castShadow receiveShadow geometry={nodes.Oak_Wall_Sign.geometry} material={materials.oak_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Double_Stone_Slab.geometry} material={materials.stone} />
      <mesh castShadow receiveShadow geometry={nodes.Stone_Slab.geometry} material={materials.stone} />
      <mesh castShadow receiveShadow geometry={nodes.Stone_Stairs.geometry} material={materials.stone} />
      <mesh castShadow receiveShadow geometry={nodes.Oak_Log_1.geometry} material={materials.oak_log} />
      <mesh castShadow receiveShadow geometry={nodes.Oak_Log_2.geometry} material={materials.oak_log_top} />
      <mesh castShadow receiveShadow geometry={nodes.Dirt_Path_1.geometry} material={materials.dirt_path_top} />
      <mesh castShadow receiveShadow geometry={nodes.Dirt_Path_2.geometry} material={materials.dirt_path_side} />
    </group>
  )
}

useGLTF.preload('/chunk-100--75-lvl-1-transformed.glb')
