/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./maps/chunk-175-525-lvl-1.glb --transform --resolution --shadows -o ./maps/chunk-175-525-lvl-1-transformed.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/chunk-175-525-lvl-1-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Stone.geometry} material={materials.stone} />
      <mesh castShadow receiveShadow geometry={nodes.Stationary_Water.geometry} material={materials.water_still} />
      <mesh castShadow receiveShadow geometry={nodes.Sand.geometry} material={materials.sand} />
      <mesh castShadow receiveShadow geometry={nodes.Gravel.geometry} material={materials.gravel} />
      <mesh castShadow receiveShadow geometry={nodes.Iron_Ore.geometry} material={materials.iron_ore} />
      <mesh castShadow receiveShadow geometry={nodes.Coal_Ore.geometry} material={materials.coal_ore} />
      <mesh castShadow receiveShadow geometry={nodes.Oak_Leaves.geometry} material={materials.oak_leaves} />
      <mesh castShadow receiveShadow geometry={nodes.Chiseled_Sandstone.geometry} material={materials.chiseled_sandstone} />
      <mesh castShadow receiveShadow geometry={nodes.Torch.geometry} material={materials.torch} />
      <mesh castShadow receiveShadow geometry={nodes.Ladder.geometry} material={materials.ladder} />
      <mesh castShadow receiveShadow geometry={nodes.Fence.geometry} material={materials.oak_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Soul_Sand.geometry} material={materials.soul_sand} />
      <mesh castShadow receiveShadow geometry={nodes.Oak_Trapdoor.geometry} material={materials.oak_trapdoor} />
      <mesh castShadow receiveShadow geometry={nodes.Sandstone_Wall.geometry} material={materials.sandstone} />
      <mesh castShadow receiveShadow geometry={nodes.Oak_Button.geometry} material={materials.oak_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Stripped_Birch_Wood.geometry} material={materials.stripped_birch_log} />
      <mesh castShadow receiveShadow geometry={nodes.Sandstone_1.geometry} material={materials.sandstone_top} />
      <mesh castShadow receiveShadow geometry={nodes.Sandstone_2.geometry} material={materials.sandstone} />
      <mesh castShadow receiveShadow geometry={nodes.Cut_Sandstone_1.geometry} material={materials.sandstone_top} />
      <mesh castShadow receiveShadow geometry={nodes.Cut_Sandstone_2.geometry} material={materials.cut_sandstone} />
      <mesh castShadow receiveShadow geometry={nodes.Sandstone_Slab_1.geometry} material={materials.sandstone_top} />
      <mesh castShadow receiveShadow geometry={nodes.Sandstone_Slab_2.geometry} material={materials.sandstone} />
      <mesh castShadow receiveShadow geometry={nodes.Oak_Door_1.geometry} material={materials.oak_door_top} />
      <mesh castShadow receiveShadow geometry={nodes.Oak_Door_2.geometry} material={materials.oak_door_bottom} />
      <mesh castShadow receiveShadow geometry={nodes.Sandstone_Stairs_1.geometry} material={materials.sandstone_top} />
      <mesh castShadow receiveShadow geometry={nodes.Sandstone_Stairs_2.geometry} material={materials.sandstone} />
      <mesh castShadow receiveShadow geometry={nodes.Sandstone_Stairs_3.geometry} material={materials.sandstone_bottom} />
    </group>
  )
}

useGLTF.preload('/chunk-175-525-lvl-1-transformed.glb')
