/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./maps/chunk-125-425-lvl-1.glb --transform --resolution --shadows -o ./maps/chunk-125-425-lvl-1.glb-transformed.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/chunk-125-425-lvl-1-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Stone.geometry} material={materials.stone} />
      <mesh castShadow receiveShadow geometry={nodes.Granite.geometry} material={materials.granite} />
      <mesh castShadow receiveShadow geometry={nodes.Diorite.geometry} material={materials.diorite} />
      <mesh castShadow receiveShadow geometry={nodes.Andesite.geometry} material={materials.andesite} />
      <mesh castShadow receiveShadow geometry={nodes.Dirt.geometry} material={materials.dirt} />
      <mesh castShadow receiveShadow geometry={nodes.Coal_Ore.geometry} material={materials.coal_ore} />
      <mesh castShadow receiveShadow geometry={nodes.Oak_Leaves.geometry} material={materials.oak_leaves} />
      <mesh castShadow receiveShadow geometry={nodes.Jungle_Leaves.geometry} material={materials.jungle_leaves} />
      <mesh castShadow receiveShadow geometry={nodes.Grass.geometry} material={materials.grass} />
      <mesh castShadow receiveShadow geometry={nodes.Torch.geometry} material={materials.torch} />
      <mesh castShadow receiveShadow geometry={nodes.Oak_Stairs.geometry} material={materials.oak_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Wheat.geometry} material={materials.wheat_stage7} />
      <mesh castShadow receiveShadow geometry={nodes.Fence.geometry} material={materials.oak_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Stone_Brick_Stairs.geometry} material={materials.stone_bricks} />
      <mesh castShadow receiveShadow geometry={nodes.Oak_Slab.geometry} material={materials.oak_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Sunflower.geometry} material={materials.sunflower_bottom} />
      <mesh castShadow receiveShadow geometry={nodes.Large_Fern.geometry} material={materials.large_fern_bottom} />
      <mesh castShadow receiveShadow geometry={nodes.Stripped_Birch_Wood.geometry} material={materials.stripped_birch_log} />
      <mesh castShadow receiveShadow geometry={nodes.Grass_Block_1.geometry} material={materials.grass_block_top} />
      <mesh castShadow receiveShadow geometry={nodes.Grass_Block_2.geometry} material={materials.dirt} />
      <mesh castShadow receiveShadow geometry={nodes.Grass_Block_3.geometry} material={materials.grass_block_side} />
      <mesh castShadow receiveShadow geometry={nodes.Stationary_Water_1.geometry} material={materials.water_still} />
      <mesh castShadow receiveShadow geometry={nodes.Stationary_Water_2.geometry} material={materials.water_flow} />
      <mesh castShadow receiveShadow geometry={nodes.Sandstone_1.geometry} material={materials.sandstone_top} />
      <mesh castShadow receiveShadow geometry={nodes.Sandstone_2.geometry} material={materials.sandstone} />
      <mesh castShadow receiveShadow geometry={nodes.Sandstone_3.geometry} material={materials.sandstone_bottom} />
      <mesh castShadow receiveShadow geometry={nodes.Double_Sandstone_Slab_1.geometry} material={materials.sandstone_top} />
      <mesh castShadow receiveShadow geometry={nodes.Double_Sandstone_Slab_2.geometry} material={materials.sandstone} />
      <mesh castShadow receiveShadow geometry={nodes.Double_Sandstone_Slab_3.geometry} material={materials.sandstone_bottom} />
      <mesh castShadow receiveShadow geometry={nodes.Sandstone_Slab_1.geometry} material={materials.sandstone_bottom} />
      <mesh castShadow receiveShadow geometry={nodes.Sandstone_Slab_2.geometry} material={materials.sandstone_top} />
      <mesh castShadow receiveShadow geometry={nodes.Sandstone_Slab_3.geometry} material={materials.sandstone} />
      <mesh castShadow receiveShadow geometry={nodes.Farmland_1.geometry} material={materials.dirt} />
      <mesh castShadow receiveShadow geometry={nodes.Farmland_2.geometry} material={materials.farmland_moist} />
      <mesh castShadow receiveShadow geometry={nodes.Sandstone_Stairs_1.geometry} material={materials.sandstone_top} />
      <mesh castShadow receiveShadow geometry={nodes.Sandstone_Stairs_2.geometry} material={materials.sandstone} />
      <mesh castShadow receiveShadow geometry={nodes.Sandstone_Stairs_3.geometry} material={materials.sandstone_bottom} />
      <mesh castShadow receiveShadow geometry={nodes.Dirt_Path_1.geometry} material={materials.dirt_path_top} />
      <mesh castShadow receiveShadow geometry={nodes.Dirt_Path_2.geometry} material={materials.dirt_path_side} />
    </group>
  )
}

useGLTF.preload('/chunk-125-425-lvl-1-transformed.glb')
