/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./maps/chunk0-200-lvl-1.glb --transform --resolution --shadows -o ./maps/chunk0-200-lvl-1.glb-transformed.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/chunk0-200-lvl-1-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Grass_Block.geometry} material={materials.grass_block_top} />
      <mesh castShadow receiveShadow geometry={nodes.Grass.geometry} material={materials.grass} />
      <mesh castShadow receiveShadow geometry={nodes.Fern.geometry} material={materials.fern} />
      <mesh castShadow receiveShadow geometry={nodes.Dandelion.geometry} material={materials.dandelion} />
      <mesh castShadow receiveShadow geometry={nodes.Double_Tallgrass_1.geometry} material={materials.tall_grass_bottom} />
      <mesh castShadow receiveShadow geometry={nodes.Double_Tallgrass_2.geometry} material={materials.tall_grass_top} />
      <mesh castShadow receiveShadow geometry={nodes.Large_Fern_1.geometry} material={materials.large_fern_bottom} />
      <mesh castShadow receiveShadow geometry={nodes.Large_Fern_2.geometry} material={materials.large_fern_top} />
    </group>
  )
}

useGLTF.preload('/chunk0-200-lvl-1-transformed.glb')
