/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./maps/chunk-225-475-lvl-1.glb --transform --resolution --shadows -o ./maps/chunk-225-475-lvl-1-transformed.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/chunk-225-475-lvl-1-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Dirt.geometry} material={materials.dirt} />
      <mesh castShadow receiveShadow geometry={nodes.Oak_Sapling.geometry} material={materials.oak_sapling} />
      <mesh castShadow receiveShadow geometry={nodes.Piston.geometry} material={materials.piston_side} />
      <mesh castShadow receiveShadow geometry={nodes.Dandelion.geometry} material={materials.dandelion} />
      <mesh castShadow receiveShadow geometry={nodes.Brown_Mushroom.geometry} material={materials.brown_mushroom} />
      <mesh castShadow receiveShadow geometry={nodes.Torch.geometry} material={materials.torch} />
      <mesh castShadow receiveShadow geometry={nodes.Oak_Stairs.geometry} material={materials.oak_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Oak_Wall_Sign.geometry} material={materials.oak_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Fence.geometry} material={materials.oak_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Oak_Trapdoor.geometry} material={materials.oak_trapdoor} />
      <mesh castShadow receiveShadow geometry={nodes.Fence_Gate.geometry} material={materials.oak_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Oak_Slab.geometry} material={materials.oak_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Sandstone_Wall.geometry} material={materials.sandstone} />
      <mesh castShadow receiveShadow geometry={nodes.Oak_Button.geometry} material={materials.oak_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Orange_Carpet.geometry} material={materials.orange_wool} />
      <mesh castShadow receiveShadow geometry={nodes.Light_Carpet.geometry} material={materials.light_blue_wool} />
      <mesh castShadow receiveShadow geometry={nodes.Yellow_Carpet.geometry} material={materials.yellow_wool} />
      <mesh castShadow receiveShadow geometry={nodes.Pink_Carpet.geometry} material={materials.pink_wool} />
      <mesh castShadow receiveShadow geometry={nodes.Gray_Carpet.geometry} material={materials.gray_wool} />
      <mesh castShadow receiveShadow geometry={nodes.Blue_Carpet.geometry} material={materials.blue_wool} />
      <mesh castShadow receiveShadow geometry={nodes.Red_Carpet.geometry} material={materials.red_wool} />
      <mesh castShadow receiveShadow geometry={nodes.Orange_Wall_Banner.geometry} material={materials.orange_concrete} />
      <mesh castShadow receiveShadow geometry={nodes.Magenta_Wall_Banner.geometry} material={materials.magenta_concrete} />
      <mesh castShadow receiveShadow geometry={nodes.Light_Blue_Wall_Banner.geometry} material={materials.light_blue_concrete} />
      <mesh castShadow receiveShadow geometry={nodes.Yellow_Wall_Banner.geometry} material={materials.yellow_concrete} />
      <mesh castShadow receiveShadow geometry={nodes.Pink_Wall_Banner.geometry} material={materials.pink_concrete} />
      <mesh castShadow receiveShadow geometry={nodes.Gray_Wall_Banner.geometry} material={materials.gray_concrete} />
      <mesh castShadow receiveShadow geometry={nodes.Cyan_Wall_Banner.geometry} material={materials.cyan_concrete} />
      <mesh castShadow receiveShadow geometry={nodes.Blue_Wall_Banner.geometry} material={materials.blue_concrete} />
      <mesh castShadow receiveShadow geometry={nodes.Red_Wall_Banner.geometry} material={materials.red_concrete} />
      <mesh castShadow receiveShadow geometry={nodes.Grass_Block_1.geometry} material={materials.grass_block_top} />
      <mesh castShadow receiveShadow geometry={nodes.Grass_Block_2.geometry} material={materials.dirt} />
      <mesh castShadow receiveShadow geometry={nodes.Grass_Block_3.geometry} material={materials.grass_block_side} />
      <mesh castShadow receiveShadow geometry={nodes.Stationary_Water_1.geometry} material={materials.water_still} />
      <mesh castShadow receiveShadow geometry={nodes.Stationary_Water_2.geometry} material={materials.water_flow} />
      <mesh castShadow receiveShadow geometry={nodes.Sandstone_1.geometry} material={materials.sandstone_top} />
      <mesh castShadow receiveShadow geometry={nodes.Sandstone_2.geometry} material={materials.sandstone} />
      <mesh castShadow receiveShadow geometry={nodes.Sandstone_3.geometry} material={materials.sandstone_bottom} />
      <mesh castShadow receiveShadow geometry={nodes.Chiseled_Sandstone_1.geometry} material={materials.sandstone_top} />
      <mesh castShadow receiveShadow geometry={nodes.Chiseled_Sandstone_2.geometry} material={materials.chiseled_sandstone} />
      <mesh castShadow receiveShadow geometry={nodes.Cut_Sandstone_1.geometry} material={materials.sandstone_top} />
      <mesh castShadow receiveShadow geometry={nodes.Cut_Sandstone_2.geometry} material={materials.cut_sandstone} />
      <mesh castShadow receiveShadow geometry={nodes.Bed_1.geometry} material={materials.oak_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Bed_2.geometry} material={materials.MW_bed_feet_top} />
      <mesh castShadow receiveShadow geometry={nodes.Bed_3.geometry} material={materials.MW_bed_feet_end} />
      <mesh castShadow receiveShadow geometry={nodes.Bed_4.geometry} material={materials.MW_bed_feet_side} />
      <mesh castShadow receiveShadow geometry={nodes.Double_Sandstone_Slab_1.geometry} material={materials.sandstone_top} />
      <mesh castShadow receiveShadow geometry={nodes.Double_Sandstone_Slab_2.geometry} material={materials.sandstone} />
      <mesh castShadow receiveShadow geometry={nodes.Double_Sandstone_Slab_3.geometry} material={materials.sandstone_bottom} />
      <mesh castShadow receiveShadow geometry={nodes.Sandstone_Slab_1.geometry} material={materials.sandstone_bottom} />
      <mesh castShadow receiveShadow geometry={nodes.Sandstone_Slab_2.geometry} material={materials.sandstone_top} />
      <mesh castShadow receiveShadow geometry={nodes.Sandstone_Slab_3.geometry} material={materials.sandstone} />
      <mesh castShadow receiveShadow geometry={nodes.Chest_1.geometry} material={materials.MWO_chest_top} />
      <mesh castShadow receiveShadow geometry={nodes.Chest_2.geometry} material={materials.MWO_chest_side} />
      <mesh castShadow receiveShadow geometry={nodes.Chest_3.geometry} material={materials.MWO_chest_front} />
      <mesh castShadow receiveShadow geometry={nodes.Chest_4.geometry} material={materials.MWO_chest_latch} />
      <mesh castShadow receiveShadow geometry={nodes.Oak_Door_1.geometry} material={materials.oak_door_top} />
      <mesh castShadow receiveShadow geometry={nodes.Oak_Door_2.geometry} material={materials.oak_door_bottom} />
      <mesh castShadow receiveShadow geometry={nodes.Sandstone_Stairs_1.geometry} material={materials.sandstone_top} />
      <mesh castShadow receiveShadow geometry={nodes.Sandstone_Stairs_2.geometry} material={materials.sandstone} />
      <mesh castShadow receiveShadow geometry={nodes.Sandstone_Stairs_3.geometry} material={materials.sandstone_bottom} />
      <mesh castShadow receiveShadow geometry={nodes.Flower_Pot_1.geometry} material={materials.dirt} />
      <mesh castShadow receiveShadow geometry={nodes.Flower_Pot_2.geometry} material={materials.flower_pot} />
      <mesh castShadow receiveShadow geometry={nodes.Potted_Dandelion_1.geometry} material={materials.flower_pot} />
      <mesh castShadow receiveShadow geometry={nodes.Potted_Dandelion_2.geometry} material={materials.dirt} />
      <mesh castShadow receiveShadow geometry={nodes.Potted_Brown_Mushroom_1.geometry} material={materials.flower_pot} />
      <mesh castShadow receiveShadow geometry={nodes.Potted_Brown_Mushroom_2.geometry} material={materials.dirt} />
      <mesh castShadow receiveShadow geometry={nodes.Potted_Oak_Sapling_1.geometry} material={materials.flower_pot} />
      <mesh castShadow receiveShadow geometry={nodes.Potted_Oak_Sapling_2.geometry} material={materials.dirt} />
      <mesh castShadow receiveShadow geometry={nodes.Hay_Bale_1.geometry} material={materials.hay_block_side} />
      <mesh castShadow receiveShadow geometry={nodes.Hay_Bale_2.geometry} material={materials.hay_block_top} />
      <mesh castShadow receiveShadow geometry={nodes.Cut_Sandstone_Slab_1.geometry} material={materials.sandstone_top} />
      <mesh castShadow receiveShadow geometry={nodes.Cut_Sandstone_Slab_2.geometry} material={materials.cut_sandstone} />
      <mesh castShadow receiveShadow geometry={nodes.Spruce_Door_1.geometry} material={materials.spruce_door_bottom} />
      <mesh castShadow receiveShadow geometry={nodes.Spruce_Door_2.geometry} material={materials.spruce_door_top} />
    </group>
  )
}

useGLTF.preload('/chunk-225-475-lvl-1-transformed.glb')
