/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./maps/chunk-50-100-lvl-1.glb --transform --resolution --shadows -o ./maps/chunk-50-100-lvl-1.glb-transformed.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/chunk-50-100-lvl-1-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Stationary_Lava.geometry} material={materials.lava_still} />
      <mesh castShadow receiveShadow geometry={nodes.Sand.geometry} material={materials.sand} />
      <mesh castShadow receiveShadow geometry={nodes.Torch.geometry} material={materials.torch} />
      <mesh castShadow receiveShadow geometry={nodes.Clay.geometry} material={materials.clay} />
      <mesh castShadow receiveShadow geometry={nodes.Fence.geometry} material={materials.oak_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Iron_Bars.geometry} material={materials.iron_bars} />
      <mesh castShadow receiveShadow geometry={nodes.Sandstone_Wall.geometry} material={materials.sandstone} />
      <mesh castShadow receiveShadow geometry={nodes.Lime_Terracotta.geometry} material={materials.lime_terracotta} />
      <mesh castShadow receiveShadow geometry={nodes.Smooth_Sandstone_Slab.geometry} material={materials.sandstone_top} />
      <mesh castShadow receiveShadow geometry={nodes.White_Glazed_Terracotta.geometry} material={materials.white_glazed_terracotta} />
      <mesh castShadow receiveShadow geometry={nodes.Smooth_Sandstone.geometry} material={materials.sandstone_top} />
      <mesh castShadow receiveShadow geometry={nodes.Sandstone_1.geometry} material={materials.sandstone_top} />
      <mesh castShadow receiveShadow geometry={nodes.Sandstone_2.geometry} material={materials.sandstone} />
      <mesh castShadow receiveShadow geometry={nodes.Sandstone_3.geometry} material={materials.sandstone_bottom} />
      <mesh castShadow receiveShadow geometry={nodes.Cut_Sandstone_1.geometry} material={materials.sandstone_top} />
      <mesh castShadow receiveShadow geometry={nodes.Cut_Sandstone_2.geometry} material={materials.cut_sandstone} />
      <mesh castShadow receiveShadow geometry={nodes.Bed_1.geometry} material={materials.oak_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Bed_2.geometry} material={materials.MW_bed_feet_top} />
      <mesh castShadow receiveShadow geometry={nodes.Bed_3.geometry} material={materials.MW_bed_head_top} />
      <mesh castShadow receiveShadow geometry={nodes.Bed_4.geometry} material={materials.MW_bed_feet_end} />
      <mesh castShadow receiveShadow geometry={nodes.Bed_5.geometry} material={materials.MW_bed_feet_side} />
      <mesh castShadow receiveShadow geometry={nodes.Bed_6.geometry} material={materials.MW_bed_head_side} />
      <mesh castShadow receiveShadow geometry={nodes.Bed_7.geometry} material={materials.MW_bed_head_end} />
      <mesh castShadow receiveShadow geometry={nodes.Sandstone_Slab_1.geometry} material={materials.sandstone_top} />
      <mesh castShadow receiveShadow geometry={nodes.Sandstone_Slab_2.geometry} material={materials.sandstone} />
      <mesh castShadow receiveShadow geometry={nodes.Sandstone_Slab_3.geometry} material={materials.sandstone_bottom} />
      <mesh castShadow receiveShadow geometry={nodes.Chest_1.geometry} material={materials.MWO_chest_top} />
      <mesh castShadow receiveShadow geometry={nodes.Chest_2.geometry} material={materials.MWO_chest_side} />
      <mesh castShadow receiveShadow geometry={nodes.Chest_3.geometry} material={materials.MWO_chest_front} />
      <mesh castShadow receiveShadow geometry={nodes.Chest_4.geometry} material={materials.MWO_double_chest_front_left} />
      <mesh castShadow receiveShadow geometry={nodes.Chest_5.geometry} material={materials.MWO_double_chest_front_right} />
      <mesh castShadow receiveShadow geometry={nodes.Chest_6.geometry} material={materials.MWO_double_chest_back_left} />
      <mesh castShadow receiveShadow geometry={nodes.Chest_7.geometry} material={materials.MWO_double_chest_back_right} />
      <mesh castShadow receiveShadow geometry={nodes.Chest_8.geometry} material={materials.MWO_double_chest_top_left} />
      <mesh castShadow receiveShadow geometry={nodes.Chest_9.geometry} material={materials.MWO_double_chest_top_right} />
      <mesh castShadow receiveShadow geometry={nodes.Chest_10.geometry} material={materials.MWO_chest_latch} />
      <mesh castShadow receiveShadow geometry={nodes.Smithing_Table_1.geometry} material={materials.smithing_table_top} />
      <mesh castShadow receiveShadow geometry={nodes.Smithing_Table_2.geometry} material={materials.smithing_table_side} />
      <mesh castShadow receiveShadow geometry={nodes.Smithing_Table_3.geometry} material={materials.smithing_table_front} />
      <mesh castShadow receiveShadow geometry={nodes.Furnace_1.geometry} material={materials.furnace_front} />
      <mesh castShadow receiveShadow geometry={nodes.Furnace_2.geometry} material={materials.furnace_side} />
      <mesh castShadow receiveShadow geometry={nodes.Sandstone_Stairs_1.geometry} material={materials.sandstone_top} />
      <mesh castShadow receiveShadow geometry={nodes.Sandstone_Stairs_2.geometry} material={materials.sandstone} />
      <mesh castShadow receiveShadow geometry={nodes.Sandstone_Stairs_3.geometry} material={materials.sandstone_bottom} />
      <mesh castShadow receiveShadow geometry={nodes.Cut_Red_Sandstone_1.geometry} material={materials.cut_red_sandstone} />
      <mesh castShadow receiveShadow geometry={nodes.Cut_Red_Sandstone_2.geometry} material={materials.red_sandstone_top} />
      <mesh castShadow receiveShadow geometry={nodes.Red_Sandstone_Slab_1.geometry} material={materials.red_sandstone_top} />
      <mesh castShadow receiveShadow geometry={nodes.Red_Sandstone_Slab_2.geometry} material={materials.red_sandstone_bottom} />
      <mesh castShadow receiveShadow geometry={nodes.Red_Sandstone_Slab_3.geometry} material={materials.red_sandstone} />
      <mesh castShadow receiveShadow geometry={nodes.Spruce_Door_1.geometry} material={materials.spruce_door_bottom} />
      <mesh castShadow receiveShadow geometry={nodes.Spruce_Door_2.geometry} material={materials.spruce_door_top} />
      <mesh castShadow receiveShadow geometry={nodes.Jungle_Door_1.geometry} material={materials.jungle_door_bottom} />
      <mesh castShadow receiveShadow geometry={nodes.Jungle_Door_2.geometry} material={materials.jungle_door_top} />
      <mesh castShadow receiveShadow geometry={nodes.Stone_Cutter_1.geometry} material={materials.stonecutter_top} />
      <mesh castShadow receiveShadow geometry={nodes.Stone_Cutter_2.geometry} material={materials.stonecutter_side} />
      <mesh castShadow receiveShadow geometry={nodes.Stone_Cutter_3.geometry} material={materials.stonecutter_saw} />
    </group>
  )
}

useGLTF.preload('/chunk-50-100-lvl-1-transformed.glb')
