/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./maps/chunk125-150-lvl-1.glb --transform --resolution --shadows -o ./maps/chunk125-150-lvl-1.glb-transformed.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/chunk125-150-lvl-1-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Stone.geometry} material={materials.stone} />
      <mesh castShadow receiveShadow geometry={nodes.Dirt.geometry} material={materials.dirt} />
      <mesh castShadow receiveShadow geometry={nodes.Cobblestone.geometry} material={materials.cobblestone} />
      <mesh castShadow receiveShadow geometry={nodes.Stationary_Water.geometry} material={materials.water_still} />
      <mesh castShadow receiveShadow geometry={nodes.Gravel.geometry} material={materials.gravel} />
      <mesh castShadow receiveShadow geometry={nodes.Birch_Leaves.geometry} material={materials.birch_leaves} />
      <mesh castShadow receiveShadow geometry={nodes.Grass.geometry} material={materials.grass} />
      <mesh castShadow receiveShadow geometry={nodes.Dandelion.geometry} material={materials.dandelion} />
      <mesh castShadow receiveShadow geometry={nodes.Poppy.geometry} material={materials.poppy} />
      <mesh castShadow receiveShadow geometry={nodes.Blue_Orchid.geometry} material={materials.blue_orchid} />
      <mesh castShadow receiveShadow geometry={nodes.Cobblestone_Slab.geometry} material={materials.cobblestone} />
      <mesh castShadow receiveShadow geometry={nodes.Lever.geometry} material={materials.lever} />
      <mesh castShadow receiveShadow geometry={nodes.Stone_Button.geometry} material={materials.stone} />
      <mesh castShadow receiveShadow geometry={nodes.Sugar_Cane.geometry} material={materials.sugar_cane} />
      <mesh castShadow receiveShadow geometry={nodes.Netherrack.geometry} material={materials.netherrack} />
      <mesh castShadow receiveShadow geometry={nodes.Lily_Pad.geometry} material={materials.lily_pad} />
      <mesh castShadow receiveShadow geometry={nodes.Dark_Oak_Slab.geometry} material={materials.dark_oak_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Acacia_Leaves.geometry} material={materials.acacia_leaves} />
      <mesh castShadow receiveShadow geometry={nodes.Acacia_Wood.geometry} material={materials.acacia_log} />
      <mesh castShadow receiveShadow geometry={nodes.Grass_Block_1.geometry} material={materials.grass_block_top} />
      <mesh castShadow receiveShadow geometry={nodes.Grass_Block_2.geometry} material={materials.grass_block_side} />
    </group>
  )
}

useGLTF.preload('/chunk125-150-lvl-1-transformed.glb')
