/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./maps/chunk50-100-lvl-1.glb --transform --resolution --shadows -o ./maps/chunk50-100-lvl-1.glb-transformed.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/chunk50-100-lvl-1-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Grass_Block.geometry} material={materials.grass_block_top} />
      <mesh castShadow receiveShadow geometry={nodes.Dirt.geometry} material={materials.dirt} />
      <mesh castShadow receiveShadow geometry={nodes.Stationary_Water.geometry} material={materials.water_still} />
      <mesh castShadow receiveShadow geometry={nodes.Sand.geometry} material={materials.sand} />
      <mesh castShadow receiveShadow geometry={nodes.Torch.geometry} material={materials.torch} />
      <mesh castShadow receiveShadow geometry={nodes.Stripped_Birch_Log.geometry} material={materials.stripped_birch_log} />
      <mesh castShadow receiveShadow geometry={nodes.Smooth_Quartz_Stairs.geometry} material={materials.quartz_block_top} />
      <mesh castShadow receiveShadow geometry={nodes.Sandstone_1.geometry} material={materials.sandstone_top} />
      <mesh castShadow receiveShadow geometry={nodes.Sandstone_2.geometry} material={materials.sandstone} />
      <mesh castShadow receiveShadow geometry={nodes.Sandstone_3.geometry} material={materials.sandstone_bottom} />
      <mesh castShadow receiveShadow geometry={nodes.Block_of_Quartz_1.geometry} material={materials.quartz_pillar} />
      <mesh castShadow receiveShadow geometry={nodes.Block_of_Quartz_2.geometry} material={materials.quartz_block_top} />
      <mesh castShadow receiveShadow geometry={nodes.Bone_Block_1.geometry} material={materials.bone_block_side} />
      <mesh castShadow receiveShadow geometry={nodes.Bone_Block_2.geometry} material={materials.bone_block_top} />
    </group>
  )
}

useGLTF.preload('/chunk50-100-lvl-1-transformed.glb')
