/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./maps/chunk-100-100-lvl-1.glb --transform --resolution --shadows -o ./maps/chunk-100-100-lvl-1.glb-transformed.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/chunk-100-100-lvl-1-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Dirt.geometry} material={materials.dirt} />
      <mesh castShadow receiveShadow geometry={nodes.Sand.geometry} material={materials.sand} />
      <mesh castShadow receiveShadow geometry={nodes.Lily_of_the_Valley.geometry} material={materials.lily_of_the_valley} />
      <mesh castShadow receiveShadow geometry={nodes.Torch.geometry} material={materials.torch} />
      <mesh castShadow receiveShadow geometry={nodes.Oak_Stairs.geometry} material={materials.oak_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Ladder.geometry} material={materials.ladder} />
      <mesh castShadow receiveShadow geometry={nodes.Fence.geometry} material={materials.oak_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Spruce_Stairs.geometry} material={materials.spruce_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Red_Sandstone_Wall.geometry} material={materials.red_sandstone} />
      <mesh castShadow receiveShadow geometry={nodes.Carrot.geometry} material={materials.carrots_stage3} />
      <mesh castShadow receiveShadow geometry={nodes.Oak_Button.geometry} material={materials.oak_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Spruce_Trapdoor.geometry} material={materials.spruce_trapdoor} />
      <mesh castShadow receiveShadow geometry={nodes.Lantern.geometry} material={materials.lantern} />
      <mesh castShadow receiveShadow geometry={nodes.Sandstone_1.geometry} material={materials.sandstone_top} />
      <mesh castShadow receiveShadow geometry={nodes.Sandstone_2.geometry} material={materials.sandstone} />
      <mesh castShadow receiveShadow geometry={nodes.Sandstone_3.geometry} material={materials.sandstone_bottom} />
      <mesh castShadow receiveShadow geometry={nodes.Cut_Sandstone_1.geometry} material={materials.sandstone_top} />
      <mesh castShadow receiveShadow geometry={nodes.Cut_Sandstone_2.geometry} material={materials.cut_sandstone} />
      <mesh castShadow receiveShadow geometry={nodes.Bed_1.geometry} material={materials.oak_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Bed_2.geometry} material={materials.MW_bed_feet_top} />
      <mesh castShadow receiveShadow geometry={nodes.Bed_3.geometry} material={materials.MW_bed_head_top} />
      <mesh castShadow receiveShadow geometry={nodes.Bed_4.geometry} material={materials.MW_bed_feet_end} />
      <mesh castShadow receiveShadow geometry={nodes.Bed_5.geometry} material={materials.MW_bed_feet_side} />
      <mesh castShadow receiveShadow geometry={nodes.Bed_6.geometry} material={materials.MW_bed_head_side} />
      <mesh castShadow receiveShadow geometry={nodes.Bed_7.geometry} material={materials.MW_bed_head_end} />
      <mesh castShadow receiveShadow geometry={nodes.Sandstone_Slab_1.geometry} material={materials.sandstone_top} />
      <mesh castShadow receiveShadow geometry={nodes.Sandstone_Slab_2.geometry} material={materials.sandstone} />
      <mesh castShadow receiveShadow geometry={nodes.Sandstone_Slab_3.geometry} material={materials.sandstone_bottom} />
      <mesh castShadow receiveShadow geometry={nodes.Bookshelf_1.geometry} material={materials.oak_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Bookshelf_2.geometry} material={materials.bookshelf} />
      <mesh castShadow receiveShadow geometry={nodes.Chest_1.geometry} material={materials.MWO_chest_side} />
      <mesh castShadow receiveShadow geometry={nodes.Chest_2.geometry} material={materials.MWO_double_chest_front_left} />
      <mesh castShadow receiveShadow geometry={nodes.Chest_3.geometry} material={materials.MWO_double_chest_front_right} />
      <mesh castShadow receiveShadow geometry={nodes.Chest_4.geometry} material={materials.MWO_double_chest_back_left} />
      <mesh castShadow receiveShadow geometry={nodes.Chest_5.geometry} material={materials.MWO_double_chest_back_right} />
      <mesh castShadow receiveShadow geometry={nodes.Chest_6.geometry} material={materials.MWO_double_chest_top_left} />
      <mesh castShadow receiveShadow geometry={nodes.Chest_7.geometry} material={materials.MWO_double_chest_top_right} />
      <mesh castShadow receiveShadow geometry={nodes.Chest_8.geometry} material={materials.MWO_chest_latch} />
      <mesh castShadow receiveShadow geometry={nodes.Cartography_Table_1.geometry} material={materials.cartography_table_top} />
      <mesh castShadow receiveShadow geometry={nodes.Cartography_Table_2.geometry} material={materials.cartography_table_side1} />
      <mesh castShadow receiveShadow geometry={nodes.Cartography_Table_3.geometry} material={materials.cartography_table_side2} />
      <mesh castShadow receiveShadow geometry={nodes.Cartography_Table_4.geometry} material={materials.cartography_table_side3} />
      <mesh castShadow receiveShadow geometry={nodes.Fletching_Table_1.geometry} material={materials.fletching_table_top} />
      <mesh castShadow receiveShadow geometry={nodes.Fletching_Table_2.geometry} material={materials.fletching_table_side} />
      <mesh castShadow receiveShadow geometry={nodes.Fletching_Table_3.geometry} material={materials.fletching_table_front} />
      <mesh castShadow receiveShadow geometry={nodes.Farmland_1.geometry} material={materials.dirt} />
      <mesh castShadow receiveShadow geometry={nodes.Farmland_2.geometry} material={materials.farmland_moist} />
      <mesh castShadow receiveShadow geometry={nodes.Sandstone_Stairs_1.geometry} material={materials.sandstone_top} />
      <mesh castShadow receiveShadow geometry={nodes.Sandstone_Stairs_2.geometry} material={materials.sandstone} />
      <mesh castShadow receiveShadow geometry={nodes.Sandstone_Stairs_3.geometry} material={materials.sandstone_bottom} />
      <mesh castShadow receiveShadow geometry={nodes.Cut_Red_Sandstone_1.geometry} material={materials.cut_red_sandstone} />
      <mesh castShadow receiveShadow geometry={nodes.Cut_Red_Sandstone_2.geometry} material={materials.red_sandstone_top} />
      <mesh castShadow receiveShadow geometry={nodes.Red_Sandstone_Stairs_1.geometry} material={materials.red_sandstone_top} />
      <mesh castShadow receiveShadow geometry={nodes.Red_Sandstone_Stairs_2.geometry} material={materials.red_sandstone_bottom} />
      <mesh castShadow receiveShadow geometry={nodes.Red_Sandstone_Stairs_3.geometry} material={materials.red_sandstone} />
      <mesh castShadow receiveShadow geometry={nodes.Cut_Sandstone_Slab_2.geometry} material={materials.sandstone_top} />
      <mesh castShadow receiveShadow geometry={nodes.Cut_Sandstone_Slab_3.geometry} material={materials.cut_sandstone} />
      <mesh castShadow receiveShadow geometry={nodes.Cut_Sandstone_Slab_1_1.geometry} material={materials.cut_sandstone} />
      <mesh castShadow receiveShadow geometry={nodes.Cut_Sandstone_Slab_1_2.geometry} material={materials.sandstone_top} />
      <mesh castShadow receiveShadow geometry={nodes.Spruce_Door_1.geometry} material={materials.spruce_door_bottom} />
      <mesh castShadow receiveShadow geometry={nodes.Spruce_Door_2.geometry} material={materials.spruce_door_top} />
      <mesh castShadow receiveShadow geometry={nodes.Composter_1.geometry} material={materials.composter_top} />
      <mesh castShadow receiveShadow geometry={nodes.Composter_2.geometry} material={materials.composter_side} />
      <mesh castShadow receiveShadow geometry={nodes.Composter_3.geometry} material={materials.composter_bottom} />
    </group>
  )
}

useGLTF.preload('/chunk-100-100-lvl-1-transformed.glb')
