/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./maps/chunk-175-575-lvl-1.glb --transform --resolution --shadows -o ./maps/chunk-175-575-lvl-1-transformed.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/chunk-175-575-lvl-1-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Stone.geometry} material={materials.stone} />
      <mesh castShadow receiveShadow geometry={nodes.Granite.geometry} material={materials.granite} />
      <mesh castShadow receiveShadow geometry={nodes.Diorite.geometry} material={materials.diorite} />
      <mesh castShadow receiveShadow geometry={nodes.Andesite.geometry} material={materials.andesite} />
      <mesh castShadow receiveShadow geometry={nodes.Dirt.geometry} material={materials.dirt} />
      <mesh castShadow receiveShadow geometry={nodes.Stationary_Water.geometry} material={materials.water_still} />
      <mesh castShadow receiveShadow geometry={nodes.Sand.geometry} material={materials.sand} />
      <mesh castShadow receiveShadow geometry={nodes.Gravel.geometry} material={materials.gravel} />
      <mesh castShadow receiveShadow geometry={nodes.Coal_Ore.geometry} material={materials.coal_ore} />
      <mesh castShadow receiveShadow geometry={nodes.Spruce_Leaves.geometry} material={materials.spruce_leaves} />
      <mesh castShadow receiveShadow geometry={nodes.Grass.geometry} material={materials.grass} />
      <mesh castShadow receiveShadow geometry={nodes.Dandelion.geometry} material={materials.dandelion} />
      <mesh castShadow receiveShadow geometry={nodes.Poppy.geometry} material={materials.poppy} />
      <mesh castShadow receiveShadow geometry={nodes.Oxeye_Daisy.geometry} material={materials.oxeye_daisy} />
      <mesh castShadow receiveShadow geometry={nodes['Redstone_Torch_(active)'].geometry} material={materials.redstone_torch} />
      <mesh castShadow receiveShadow geometry={nodes.Snow.geometry} material={materials.snow} />
      <mesh castShadow receiveShadow geometry={nodes.Grass_Block_1.geometry} material={materials.grass_block_top} />
      <mesh castShadow receiveShadow geometry={nodes.Grass_Block_2.geometry} material={materials.grass_block_side} />
      <mesh castShadow receiveShadow geometry={nodes.Spruce_Log_1.geometry} material={materials.spruce_log} />
      <mesh castShadow receiveShadow geometry={nodes.Spruce_Log_2.geometry} material={materials.spruce_log_top} />
      <mesh castShadow receiveShadow geometry={nodes.Sunflower_1.geometry} material={materials.sunflower_back} />
      <mesh castShadow receiveShadow geometry={nodes.Sunflower_2.geometry} material={materials.sunflower_front} />
      <mesh castShadow receiveShadow geometry={nodes.Sunflower_3.geometry} material={materials.sunflower_bottom} />
      <mesh castShadow receiveShadow geometry={nodes.Sunflower_4.geometry} material={materials.sunflower_top} />
      <mesh castShadow receiveShadow geometry={nodes.Double_Tallgrass_1.geometry} material={materials.tall_grass_bottom} />
      <mesh castShadow receiveShadow geometry={nodes.Double_Tallgrass_2.geometry} material={materials.tall_grass_top} />
    </group>
  )
}

useGLTF.preload('/chunk-175-575-lvl-1-transformed.glb')
