/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./maps/chunk-125-450-lvl-1.glb --transform --resolution --shadows -o ./maps/chunk-125-450-lvl-1.glb-transformed.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/chunk-125-450-lvl-1-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Stone.geometry} material={materials.stone} />
      <mesh castShadow receiveShadow geometry={nodes.Granite.geometry} material={materials.granite} />
      <mesh castShadow receiveShadow geometry={nodes.Diorite.geometry} material={materials.diorite} />
      <mesh castShadow receiveShadow geometry={nodes.Andesite.geometry} material={materials.andesite} />
      <mesh castShadow receiveShadow geometry={nodes.Dirt.geometry} material={materials.dirt} />
      <mesh castShadow receiveShadow geometry={nodes.Oak_Planks.geometry} material={materials.oak_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Coal_Ore.geometry} material={materials.coal_ore} />
      <mesh castShadow receiveShadow geometry={nodes.Grass.geometry} material={materials.grass} />
      <mesh castShadow receiveShadow geometry={nodes.Dandelion.geometry} material={materials.dandelion} />
      <mesh castShadow receiveShadow geometry={nodes.Poppy.geometry} material={materials.poppy} />
      <mesh castShadow receiveShadow geometry={nodes.Stone_Brick_Slab.geometry} material={materials.stone_bricks} />
      <mesh castShadow receiveShadow geometry={nodes.Torch.geometry} material={materials.torch} />
      <mesh castShadow receiveShadow geometry={nodes.Oak_Stairs.geometry} material={materials.oak_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Wheat.geometry} material={materials.wheat_stage7} />
      <mesh castShadow receiveShadow geometry={nodes.Ladder.geometry} material={materials.ladder} />
      <mesh castShadow receiveShadow geometry={nodes.Fence.geometry} material={materials.oak_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Stone_Bricks.geometry} material={materials.stone_bricks} />
      <mesh castShadow receiveShadow geometry={nodes.Fence_Gate.geometry} material={materials.oak_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Stone_Brick_Stairs.geometry} material={materials.stone_bricks} />
      <mesh castShadow receiveShadow geometry={nodes.Double_Oak_Slab.geometry} material={materials.oak_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Oak_Slab.geometry} material={materials.oak_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Sandstone_Wall.geometry} material={materials.sandstone} />
      <mesh castShadow receiveShadow geometry={nodes.Sunflower.geometry} material={materials.sunflower_bottom} />
      <mesh castShadow receiveShadow geometry={nodes.Beetroot_Seeds.geometry} material={materials.beetroots_stage3} />
      <mesh castShadow receiveShadow geometry={nodes.Stripped_Birch_Wood.geometry} material={materials.stripped_birch_log} />
      <mesh castShadow receiveShadow geometry={nodes.Smooth_Sandstone_Stairs.geometry} material={materials.sandstone_top} />
      <mesh castShadow receiveShadow geometry={nodes.Grass_Block_1.geometry} material={materials.grass_block_top} />
      <mesh castShadow receiveShadow geometry={nodes.Grass_Block_2.geometry} material={materials.grass_block_side} />
      <mesh castShadow receiveShadow geometry={nodes.Stationary_Water_1.geometry} material={materials.water_still} />
      <mesh castShadow receiveShadow geometry={nodes.Stationary_Water_2.geometry} material={materials.water_flow} />
      <mesh castShadow receiveShadow geometry={nodes.Sandstone_1.geometry} material={materials.sandstone_top} />
      <mesh castShadow receiveShadow geometry={nodes.Sandstone_2.geometry} material={materials.sandstone} />
      <mesh castShadow receiveShadow geometry={nodes.Sandstone_3.geometry} material={materials.sandstone_bottom} />
      <mesh castShadow receiveShadow geometry={nodes.Cut_Sandstone_1.geometry} material={materials.sandstone_top} />
      <mesh castShadow receiveShadow geometry={nodes.Cut_Sandstone_2.geometry} material={materials.cut_sandstone} />
      <mesh castShadow receiveShadow geometry={nodes.Double_Sandstone_Slab_1.geometry} material={materials.sandstone_top} />
      <mesh castShadow receiveShadow geometry={nodes.Double_Sandstone_Slab_2.geometry} material={materials.sandstone} />
      <mesh castShadow receiveShadow geometry={nodes.Sandstone_Slab_1.geometry} material={materials.sandstone} />
      <mesh castShadow receiveShadow geometry={nodes.Sandstone_Slab_2.geometry} material={materials.sandstone_top} />
      <mesh castShadow receiveShadow geometry={nodes.Sandstone_Slab_3.geometry} material={materials.sandstone_bottom} />
      <mesh castShadow receiveShadow geometry={nodes.Chest_1.geometry} material={materials.MWO_chest_top} />
      <mesh castShadow receiveShadow geometry={nodes.Chest_2.geometry} material={materials.MWO_chest_side} />
      <mesh castShadow receiveShadow geometry={nodes.Chest_3.geometry} material={materials.MWO_chest_front} />
      <mesh castShadow receiveShadow geometry={nodes.Chest_4.geometry} material={materials.MWO_double_chest_front_left} />
      <mesh castShadow receiveShadow geometry={nodes.Chest_5.geometry} material={materials.MWO_double_chest_front_right} />
      <mesh castShadow receiveShadow geometry={nodes.Chest_6.geometry} material={materials.MWO_double_chest_back_left} />
      <mesh castShadow receiveShadow geometry={nodes.Chest_7.geometry} material={materials.MWO_double_chest_back_right} />
      <mesh castShadow receiveShadow geometry={nodes.Chest_8.geometry} material={materials.MWO_double_chest_top_left} />
      <mesh castShadow receiveShadow geometry={nodes.Chest_9.geometry} material={materials.MWO_double_chest_top_right} />
      <mesh castShadow receiveShadow geometry={nodes.Chest_10.geometry} material={materials.MWO_chest_latch} />
      <mesh castShadow receiveShadow geometry={nodes.Farmland_1.geometry} material={materials.dirt} />
      <mesh castShadow receiveShadow geometry={nodes.Farmland_2.geometry} material={materials.farmland_moist} />
      <mesh castShadow receiveShadow geometry={nodes.Oak_Door_1.geometry} material={materials.oak_door_top} />
      <mesh castShadow receiveShadow geometry={nodes.Oak_Door_2.geometry} material={materials.oak_door_bottom} />
      <mesh castShadow receiveShadow geometry={nodes.Sandstone_Stairs_1.geometry} material={materials.sandstone_top} />
      <mesh castShadow receiveShadow geometry={nodes.Sandstone_Stairs_2.geometry} material={materials.sandstone} />
      <mesh castShadow receiveShadow geometry={nodes.Sandstone_Stairs_3.geometry} material={materials.sandstone_bottom} />
      <mesh castShadow receiveShadow geometry={nodes.Flower_Pot_1.geometry} material={materials.dirt} />
      <mesh castShadow receiveShadow geometry={nodes.Flower_Pot_2.geometry} material={materials.flower_pot} />
      <mesh castShadow receiveShadow geometry={nodes.Cut_Sandstone_Slab_1.geometry} material={materials.sandstone_top} />
      <mesh castShadow receiveShadow geometry={nodes.Cut_Sandstone_Slab_2.geometry} material={materials.cut_sandstone} />
      <mesh castShadow receiveShadow geometry={nodes.Dirt_Path_1.geometry} material={materials.dirt_path_top} />
      <mesh castShadow receiveShadow geometry={nodes.Dirt_Path_2.geometry} material={materials.dirt_path_side} />
    </group>
  )
}

useGLTF.preload('/chunk-125-450-lvl-1-transformed.glb')
