/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./maps/chunk-75-25-lvl-1.glb --transform --resolution --shadows -o ./maps/chunk-75-25-lvl-1.glb-transformed.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/chunk-75-25-lvl-1-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Stone.geometry} material={materials.stone} />
      <mesh castShadow receiveShadow geometry={nodes.Oak_Planks.geometry} material={materials.oak_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Birch_Wood_Planks.geometry} material={materials.birch_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Sand.geometry} material={materials.sand} />
      <mesh castShadow receiveShadow geometry={nodes.Cornflower.geometry} material={materials.cornflower} />
      <mesh castShadow receiveShadow geometry={nodes.Torch.geometry} material={materials.torch} />
      <mesh castShadow receiveShadow geometry={nodes.Ladder.geometry} material={materials.ladder} />
      <mesh castShadow receiveShadow geometry={nodes.Fence.geometry} material={materials.oak_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Oak_Trapdoor.geometry} material={materials.oak_trapdoor} />
      <mesh castShadow receiveShadow geometry={nodes.Oak_Slab.geometry} material={materials.oak_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Birch_Slab.geometry} material={materials.birch_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Sandstone_Wall.geometry} material={materials.sandstone} />
      <mesh castShadow receiveShadow geometry={nodes.Oak_Button.geometry} material={materials.oak_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Spruce_Button.geometry} material={materials.spruce_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Grass_Block_1.geometry} material={materials.grass_block_top} />
      <mesh castShadow receiveShadow geometry={nodes.Grass_Block_2.geometry} material={materials.grass_block_side} />
      <mesh castShadow receiveShadow geometry={nodes.Sandstone_1.geometry} material={materials.sandstone_top} />
      <mesh castShadow receiveShadow geometry={nodes.Sandstone_2.geometry} material={materials.sandstone} />
      <mesh castShadow receiveShadow geometry={nodes.Sandstone_3.geometry} material={materials.sandstone_bottom} />
      <mesh castShadow receiveShadow geometry={nodes.Cut_Sandstone_1.geometry} material={materials.sandstone_top} />
      <mesh castShadow receiveShadow geometry={nodes.Cut_Sandstone_2.geometry} material={materials.cut_sandstone} />
      <mesh castShadow receiveShadow geometry={nodes.Sandstone_Slab_1.geometry} material={materials.sandstone_top} />
      <mesh castShadow receiveShadow geometry={nodes.Sandstone_Slab_2.geometry} material={materials.sandstone} />
      <mesh castShadow receiveShadow geometry={nodes.Sandstone_Slab_3.geometry} material={materials.sandstone_bottom} />
      <mesh castShadow receiveShadow geometry={nodes.Bookshelf_1.geometry} material={materials.oak_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Bookshelf_2.geometry} material={materials.bookshelf} />
      <mesh castShadow receiveShadow geometry={nodes.Sandstone_Stairs_1.geometry} material={materials.sandstone_top} />
      <mesh castShadow receiveShadow geometry={nodes.Sandstone_Stairs_2.geometry} material={materials.sandstone} />
      <mesh castShadow receiveShadow geometry={nodes.Sandstone_Stairs_3.geometry} material={materials.sandstone_bottom} />
      <mesh castShadow receiveShadow geometry={nodes.Potted_Cornflower_1.geometry} material={materials.dirt} />
      <mesh castShadow receiveShadow geometry={nodes.Potted_Cornflower_2.geometry} material={materials.flower_pot} />
      <mesh castShadow receiveShadow geometry={nodes.Hay_Bale_1.geometry} material={materials.hay_block_side} />
      <mesh castShadow receiveShadow geometry={nodes.Hay_Bale_2.geometry} material={materials.hay_block_top} />
      <mesh castShadow receiveShadow geometry={nodes.Cut_Red_Sandstone_1.geometry} material={materials.cut_red_sandstone} />
      <mesh castShadow receiveShadow geometry={nodes.Cut_Red_Sandstone_2.geometry} material={materials.red_sandstone_top} />
      <mesh castShadow receiveShadow geometry={nodes.Cut_Red_Sandstone_Slab_1.geometry} material={materials.red_sandstone_top} />
      <mesh castShadow receiveShadow geometry={nodes.Cut_Red_Sandstone_Slab_2.geometry} material={materials.cut_red_sandstone} />
      <mesh castShadow receiveShadow geometry={nodes.Spruce_Door_1.geometry} material={materials.spruce_door_bottom} />
      <mesh castShadow receiveShadow geometry={nodes.Spruce_Door_2.geometry} material={materials.spruce_door_top} />
    </group>
  )
}

useGLTF.preload('/chunk-75-25-lvl-1-transformed.glb')
