/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./maps/chunk-25-0-lvl-1.glb --transform --resolution --shadows -o ./maps/chunk-25-0-lvl-1.glb-transformed.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/chunk-25-0-lvl-1-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Stone.geometry} material={materials.stone} />
      <mesh castShadow receiveShadow geometry={nodes.Grass_Block.geometry} material={materials.grass_block_top} />
      <mesh castShadow receiveShadow geometry={nodes.Dirt.geometry} material={materials.dirt} />
      <mesh castShadow receiveShadow geometry={nodes.Oak_Planks.geometry} material={materials.oak_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Oak_Sapling.geometry} material={materials.oak_sapling} />
      <mesh castShadow receiveShadow geometry={nodes.Sand.geometry} material={materials.sand} />
      <mesh castShadow receiveShadow geometry={nodes.Grass.geometry} material={materials.grass} />
      <mesh castShadow receiveShadow geometry={nodes.Piston.geometry} material={materials.piston_side} />
      <mesh castShadow receiveShadow geometry={nodes.Red_Wool.geometry} material={materials.red_wool} />
      <mesh castShadow receiveShadow geometry={nodes.Poppy.geometry} material={materials.poppy} />
      <mesh castShadow receiveShadow geometry={nodes.Blue_Orchid.geometry} material={materials.blue_orchid} />
      <mesh castShadow receiveShadow geometry={nodes.Torch.geometry} material={materials.torch} />
      <mesh castShadow receiveShadow geometry={nodes.Oak_Stairs.geometry} material={materials.oak_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Redstone_Wire_power_0.geometry} material={materials.MWO_redstone_dust_dot_off} />
      <mesh castShadow receiveShadow geometry={nodes.Oak_Wall_Sign.geometry} material={materials.oak_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Stone_Bricks.geometry} material={materials.stone_bricks} />
      <mesh castShadow receiveShadow geometry={nodes.Iron_Bars.geometry} material={materials.iron_bars} />
      <mesh castShadow receiveShadow geometry={nodes.Spruce_Slab.geometry} material={materials.spruce_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Spruce_Stairs.geometry} material={materials.spruce_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Stone_Brick_Wall.geometry} material={materials.stone_bricks} />
      <mesh castShadow receiveShadow geometry={nodes.Sandstone_Wall.geometry} material={materials.sandstone} />
      <mesh castShadow receiveShadow geometry={nodes.Acacia_Leaves.geometry} material={materials.acacia_leaves} />
      <mesh castShadow receiveShadow geometry={nodes.Spruce_Fence.geometry} material={materials.spruce_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Spruce_Trapdoor.geometry} material={materials.spruce_trapdoor} />
      <mesh castShadow receiveShadow geometry={nodes.Spruce_Button.geometry} material={materials.spruce_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Red_Wall_Banner.geometry} material={materials.red_concrete} />
      <mesh castShadow receiveShadow geometry={nodes.Chain.geometry} material={materials.chain} />
      <mesh castShadow receiveShadow geometry={nodes.Smooth_Sandstone_Stairs.geometry} material={materials.sandstone_top} />
      <mesh castShadow receiveShadow geometry={nodes.Sandstone_1.geometry} material={materials.sandstone_top} />
      <mesh castShadow receiveShadow geometry={nodes.Sandstone_2.geometry} material={materials.sandstone} />
      <mesh castShadow receiveShadow geometry={nodes.Sandstone_3.geometry} material={materials.sandstone_bottom} />
      <mesh castShadow receiveShadow geometry={nodes.Cut_Sandstone_1.geometry} material={materials.sandstone_top} />
      <mesh castShadow receiveShadow geometry={nodes.Cut_Sandstone_2.geometry} material={materials.cut_sandstone} />
      <mesh castShadow receiveShadow geometry={nodes.Furnace_1.geometry} material={materials.furnace_front} />
      <mesh castShadow receiveShadow geometry={nodes.Furnace_2.geometry} material={materials.furnace_top} />
      <mesh castShadow receiveShadow geometry={nodes.Sandstone_Stairs_1.geometry} material={materials.sandstone_top} />
      <mesh castShadow receiveShadow geometry={nodes.Sandstone_Stairs_2.geometry} material={materials.sandstone} />
      <mesh castShadow receiveShadow geometry={nodes.Sandstone_Stairs_3.geometry} material={materials.sandstone_bottom} />
      <mesh castShadow receiveShadow geometry={nodes.Potted_Oak_Sapling_1.geometry} material={materials.dirt} />
      <mesh castShadow receiveShadow geometry={nodes.Potted_Oak_Sapling_2.geometry} material={materials.flower_pot} />
      <mesh castShadow receiveShadow geometry={nodes.Block_of_Quartz_1.geometry} material={materials.quartz_block_side} />
      <mesh castShadow receiveShadow geometry={nodes.Block_of_Quartz_2.geometry} material={materials.quartz_block_side} />
      <mesh castShadow receiveShadow geometry={nodes.Acacia_Log_1.geometry} material={materials.acacia_log} />
      <mesh castShadow receiveShadow geometry={nodes.Acacia_Log_2.geometry} material={materials.acacia_log_top} />
      <mesh castShadow receiveShadow geometry={nodes.Double_Tallgrass_1.geometry} material={materials.tall_grass_bottom} />
      <mesh castShadow receiveShadow geometry={nodes.Double_Tallgrass_2.geometry} material={materials.tall_grass_top} />
      <mesh castShadow receiveShadow geometry={nodes.Spruce_Door_1.geometry} material={materials.spruce_door_bottom} />
      <mesh castShadow receiveShadow geometry={nodes.Spruce_Door_2.geometry} material={materials.spruce_door_top} />
      <mesh castShadow receiveShadow geometry={nodes.Stripped_Oak_Log_1.geometry} material={materials.stripped_oak_log} />
      <mesh castShadow receiveShadow geometry={nodes.Stripped_Oak_Log_2.geometry} material={materials.stripped_oak_log_top} />
      <mesh castShadow receiveShadow geometry={nodes.Stripped_Birch_Log_1.geometry} material={materials.stripped_birch_log} />
      <mesh castShadow receiveShadow geometry={nodes.Stripped_Birch_Log_2.geometry} material={materials.stripped_birch_log_top} />
      <mesh castShadow receiveShadow geometry={nodes.Lectern_1.geometry} material={materials.oak_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Lectern_2.geometry} material={materials.lectern_top} />
      <mesh castShadow receiveShadow geometry={nodes.Lectern_3.geometry} material={materials.lectern_sides} />
      <mesh castShadow receiveShadow geometry={nodes.Lectern_4.geometry} material={materials.lectern_base} />
      <mesh castShadow receiveShadow geometry={nodes.Lectern_5.geometry} material={materials.lectern_front} />
    </group>
  )
}

useGLTF.preload('/chunk-25-0-lvl-1-transformed.glb')
