/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./maps/chunk-175--25-lvl-1.glb --transform --resolution --shadows -o ./maps/chunk-175--25-lvl-1-transformed.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/chunk-175--25-lvl-1-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Stone.geometry} material={materials.stone} />
      <mesh castShadow receiveShadow geometry={nodes.Dirt.geometry} material={materials.dirt} />
      <mesh castShadow receiveShadow geometry={nodes.Double_Cobblestone_Slab.geometry} material={materials.cobblestone} />
      <mesh castShadow receiveShadow geometry={nodes.Cobblestone_Slab.geometry} material={materials.cobblestone} />
      <mesh castShadow receiveShadow geometry={nodes.Mossy_Cobblestone_Slab.geometry} material={materials.mossy_cobblestone} />
      <mesh castShadow receiveShadow geometry={nodes.Stone_Slab.geometry} material={materials.stone} />
      <mesh castShadow receiveShadow geometry={nodes.Mossy_Cobblestone_Stairs.geometry} material={materials.mossy_cobblestone} />
      <mesh castShadow receiveShadow geometry={nodes.Grass_Block_1.geometry} material={materials.grass_block_top} />
      <mesh castShadow receiveShadow geometry={nodes.Grass_Block_2.geometry} material={materials.grass_block_side} />
      <mesh castShadow receiveShadow geometry={nodes.Podzol_1.geometry} material={materials.podzol_side} />
      <mesh castShadow receiveShadow geometry={nodes.Podzol_2.geometry} material={materials.podzol_top} />
      <mesh castShadow receiveShadow geometry={nodes.Dirt_Path_1.geometry} material={materials.dirt_path_top} />
      <mesh castShadow receiveShadow geometry={nodes.Dirt_Path_2.geometry} material={materials.dirt_path_side} />
    </group>
  )
}

useGLTF.preload('/chunk-175--25-lvl-1-transformed.glb')
