/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./maps/chunk250-575-lvl-1.glb --transform --resolution --shadows -o ./maps/chunk250-575-lvl-1.glb-transformed.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/chunk250-575-lvl-1-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Sand.geometry} material={materials.sand} />
      <mesh castShadow receiveShadow geometry={nodes.Dead_Bush.geometry} material={materials.dead_bush} />
    </group>
  )
}

useGLTF.preload('/chunk250-575-lvl-1-transformed.glb')
