/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./maps/chunk0-125-lvl-1.glb --transform --resolution --shadows -o ./maps/chunk0-125-lvl-1.glb-transformed.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/chunk0-125-lvl-1-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Stone.geometry} material={materials.stone} />
      <mesh castShadow receiveShadow geometry={nodes.Grass_Block.geometry} material={materials.grass_block_top} />
      <mesh castShadow receiveShadow geometry={nodes.Dirt.geometry} material={materials.dirt} />
      <mesh castShadow receiveShadow geometry={nodes.Spruce_Wood_Planks.geometry} material={materials.spruce_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Sand.geometry} material={materials.sand} />
      <mesh castShadow receiveShadow geometry={nodes.Grass.geometry} material={materials.grass} />
      <mesh castShadow receiveShadow geometry={nodes.Blue_Wool.geometry} material={materials.blue_wool} />
      <mesh castShadow receiveShadow geometry={nodes.Torch.geometry} material={materials.torch} />
      <mesh castShadow receiveShadow geometry={nodes.Wheat.geometry} material={materials.wheat_stage7} />
      <mesh castShadow receiveShadow geometry={nodes.Farmland.geometry} material={materials.farmland} />
      <mesh castShadow receiveShadow geometry={nodes.Fence.geometry} material={materials.oak_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Oak_Slab.geometry} material={materials.oak_planks} />
      <mesh castShadow receiveShadow geometry={nodes.Chiseled_Quartz_Block.geometry} material={materials.chiseled_quartz_block_top} />
      <mesh castShadow receiveShadow geometry={nodes.Quartz_Stairs.geometry} material={materials.quartz_block_side} />
      <mesh castShadow receiveShadow geometry={nodes.Smooth_Sandstone.geometry} material={materials.sandstone_top} />
      <mesh castShadow receiveShadow geometry={nodes.Smooth_Quartz_Stairs.geometry} material={materials.quartz_block_side} />
      <mesh castShadow receiveShadow geometry={nodes.Smooth_Sandstone_Stairs.geometry} material={materials.sandstone_top} />
      <mesh castShadow receiveShadow geometry={nodes.Stationary_Water_1.geometry} material={materials.water_still} />
      <mesh castShadow receiveShadow geometry={nodes.Stationary_Water_2.geometry} material={materials.water_flow} />
      <mesh castShadow receiveShadow geometry={nodes.Sandstone_1.geometry} material={materials.sandstone_top} />
      <mesh castShadow receiveShadow geometry={nodes.Sandstone_2.geometry} material={materials.sandstone} />
      <mesh castShadow receiveShadow geometry={nodes.Sandstone_3.geometry} material={materials.sandstone_bottom} />
      <mesh castShadow receiveShadow geometry={nodes.Skeleton_Skull_1.geometry} material={materials.pumpkin_top} />
      <mesh castShadow receiveShadow geometry={nodes.Skeleton_Skull_2.geometry} material={materials.pumpkin_side} />
      <mesh castShadow receiveShadow geometry={nodes.Skeleton_Skull_3.geometry} material={materials.carved_pumpkin} />
      <mesh castShadow receiveShadow geometry={nodes.Block_of_Quartz_1.geometry} material={materials.quartz_pillar_top} />
      <mesh castShadow receiveShadow geometry={nodes.Block_of_Quartz_2.geometry} material={materials.quartz_pillar} />
      <mesh castShadow receiveShadow geometry={nodes.Block_of_Quartz_3.geometry} material={materials.quartz_block_side} />
      <mesh castShadow receiveShadow geometry={nodes.Block_of_Quartz_4.geometry} material={materials.quartz_block_side} />
      <mesh castShadow receiveShadow geometry={nodes.Bone_Block_1.geometry} material={materials.bone_block_side} />
      <mesh castShadow receiveShadow geometry={nodes.Bone_Block_2.geometry} material={materials.bone_block_top} />
      <mesh castShadow receiveShadow geometry={nodes.Composter_1.geometry} material={materials.composter_top} />
      <mesh castShadow receiveShadow geometry={nodes.Composter_2.geometry} material={materials.composter_side} />
      <mesh castShadow receiveShadow geometry={nodes.Composter_3.geometry} material={materials.composter_bottom} />
    </group>
  )
}

useGLTF.preload('/chunk0-125-lvl-1-transformed.glb')
