/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./maps/chunk225-50-lvl-1.glb --transform --resolution --shadows -o ./maps/chunk225-50-lvl-1.glb-transformed.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/chunk225-50-lvl-1-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Birch_Leaves.geometry} material={materials.birch_leaves} />
      <mesh castShadow receiveShadow geometry={nodes.Grass.geometry} material={materials.grass} />
      <mesh castShadow receiveShadow geometry={nodes.Dandelion.geometry} material={materials.dandelion} />
      <mesh castShadow receiveShadow geometry={nodes.Poppy.geometry} material={materials.poppy} />
      <mesh castShadow receiveShadow geometry={nodes.Blue_Orchid.geometry} material={materials.blue_orchid} />
      <mesh castShadow receiveShadow geometry={nodes.Azure_Bluet.geometry} material={materials.azure_bluet} />
      <mesh castShadow receiveShadow geometry={nodes.Acacia_Leaves.geometry} material={materials.acacia_leaves} />
      <mesh castShadow receiveShadow geometry={nodes.Acacia_Wood.geometry} material={materials.acacia_log} />
      <mesh castShadow receiveShadow geometry={nodes.Grass_Block_1.geometry} material={materials.grass_block_top} />
      <mesh castShadow receiveShadow geometry={nodes.Grass_Block_2.geometry} material={materials.grass_block_side} />
      <mesh castShadow receiveShadow geometry={nodes.Double_Tallgrass_1.geometry} material={materials.tall_grass_bottom} />
      <mesh castShadow receiveShadow geometry={nodes.Double_Tallgrass_2.geometry} material={materials.tall_grass_top} />
      <mesh castShadow receiveShadow geometry={nodes.Rose_Bush_1.geometry} material={materials.rose_bush_bottom} />
      <mesh castShadow receiveShadow geometry={nodes.Rose_Bush_2.geometry} material={materials.rose_bush_top} />
      <mesh castShadow receiveShadow geometry={nodes.Peony_1.geometry} material={materials.peony_bottom} />
      <mesh castShadow receiveShadow geometry={nodes.Peony_2.geometry} material={materials.peony_top} />
    </group>
  )
}

useGLTF.preload('/chunk225-50-lvl-1-transformed.glb')
