/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./maps/chunk25-50-lvl-1.glb --transform --resolution --shadows -o ./maps/chunk25-50-lvl-1.glb-transformed.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/chunk25-50-lvl-1-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Torch.geometry} material={materials.torch} />
      <mesh castShadow receiveShadow geometry={nodes.Glowstone.geometry} material={materials.glowstone} />
      <mesh castShadow receiveShadow geometry={nodes.Quartz_Stairs.geometry} material={materials.quartz_block_side} />
      <mesh castShadow receiveShadow geometry={nodes.Bone_Block.geometry} material={materials.bone_block_side} />
      <mesh castShadow receiveShadow geometry={nodes.Quartz.geometry} material={materials.quartz_block_bottom} />
      <mesh castShadow receiveShadow geometry={nodes.Quartz_Slab_1.geometry} material={materials.quartz_block_bottom} />
      <mesh castShadow receiveShadow geometry={nodes.Quartz_Slab_2.geometry} material={materials.quartz_block_side} />
      <mesh castShadow receiveShadow geometry={nodes.Quartz_Slab_3.geometry} material={materials.quartz_block_side} />
      <mesh castShadow receiveShadow geometry={nodes.Block_of_Quartz_1.geometry} material={materials.quartz_pillar} />
      <mesh castShadow receiveShadow geometry={nodes.Block_of_Quartz_2.geometry} material={materials.quartz_block_side} />
      <mesh castShadow receiveShadow geometry={nodes.Block_of_Quartz_3.geometry} material={materials.quartz_block_side} />
      <mesh castShadow receiveShadow geometry={nodes.Chiseled_Quartz_Block_1.geometry} material={materials.chiseled_quartz_block_top} />
      <mesh castShadow receiveShadow geometry={nodes.Chiseled_Quartz_Block_2.geometry} material={materials.chiseled_quartz_block} />
    </group>
  )
}

useGLTF.preload('/chunk25-50-lvl-1-transformed.glb')
